#!/usr/bin/env python3
"""Tool definitions Part 2: chinese-tax-calculator + checklist-maker + alphabetical-sorter"""
from create_tools_data import TOOLS

# Tool 3: chinese-tax-calculator
TOOLS.append(dict(
    slug='chinese-tax-calculator',
    title_cn='中国个税计算器', title_en='Chinese Tax Calculator',
    desc_cn='免费在线中国个人所得税计算器，支持2024年最新税率表。计算工资薪金、年终奖个税，纯前端本地处理。',
    desc_en='Free online Chinese individual income tax calculator. Supports 2024 latest tax rates. Calculate salary and year-end bonus tax. Pure frontend processing.',
    icon='🧮',
    cat_cn='办公工具', cat_en='Office Tools', cat_a='office-tools',
    faqs_cn=[
        ('个税起征点是多少？', '目前中国个人所得税起征点为每月5000元，加上五险一金和专项附加扣除后的余额为应纳税所得额。'),
        ('专项附加扣除有哪些？', '包括子女教育、继续教育、住房贷款利息、住房租金、赡养老人、大病医疗等。'),
        ('年终奖怎么算税？', '2027年底前，年终奖可选择单独计税或并入综合所得计税。'),
        ('税率是多少？', '综合所得适用3%-45%七级超额累进税率。'),
        ('数据安全吗？', '所有计算完全在浏览器本地运行，不会上传任何收入数据到服务器。'),
    ],
    faqs_en=[
        ('What is the tax threshold?', 'The current threshold is 5,000 CNY per month. Taxable income is the balance after deducting threshold, social insurance, and special deductions.'),
        ('What are special deductions?', 'Children education, continuing education, housing loan interest, housing rent, elderly care, and major medical expenses.'),
        ('How is year-end bonus taxed?', 'Before end of 2027, bonus can be taxed separately or combined with comprehensive income.'),
        ('What are the tax rates?', 'Comprehensive income uses 3%-45% seven-level progressive rates.'),
        ('Is my data safe?', 'All calculations run locally in your browser. No income data is uploaded.'),
    ],
    seo_cn='<h2>中国个税计算器能做什么？</h2><p>中国个税计算器是一款免费的在线工具，根据最新个人所得税法计算应纳税额。支持工资薪金和年终奖计算，纯前端本地处理，数据绝不上传。</p><h2>核心功能</h2><ul><li><strong>工资薪金个税</strong>：按月计算工资薪金个人所得税</li><li><strong>年终奖个税</strong>：支持单独计税和合并计税两种方式</li><li><strong>专项附加扣除</strong>：支持各项扣除</li><li><strong>五险一金</strong>：自动计算社保公积金扣除</li></ul><h2>使用教程</h2><ol><li><strong>输入月收入</strong>：填写税前月工资</li><li><strong>填写扣除项</strong>：输入五险一金和专项附加扣除</li><li><strong>点击计算</strong>：立即查看税后收入和纳税明细</li></ol><h2>应用场景</h2><ul><li><strong>薪资谈判</strong>：了解税后实际到手收入</li><li><strong>年终奖规划</strong>：选择最优计税方式</li><li><strong>跳槽决策</strong>：对比不同薪资方案的税后差异</li></ul><h2>扩展知识</h2><p>2019年新个税法将起征点提高至每月5000元，引入专项附加扣除制度，综合所得按年计税、按月预缴、年度汇算清缴。</p>',
    seo_en='<h2>What Can the Chinese Tax Calculator Do?</h2><p>The Chinese Tax Calculator is a free online tool that calculates individual income tax based on the latest tax law. Supports salary and year-end bonus calculations. Pure frontend, no data uploads.</p><h2>Core Features</h2><ul><li><strong>Salary tax</strong>: Monthly calculation</li><li><strong>Year-end bonus</strong>: Separate and combined methods</li><li><strong>Special deductions</strong>: Various deduction types</li><li><strong>Social insurance</strong>: Auto-calculate deductions</li></ul><h2>How to Use</h2><ol><li><strong>Enter income</strong>: Input pre-tax monthly salary</li><li><strong>Fill deductions</strong>: Enter social insurance and special deductions</li><li><strong>Calculate</strong>: View after-tax income and breakdown</li></ol><h2>Use Cases</h2><ul><li><strong>Salary negotiation</strong>: Know actual take-home pay</li><li><strong>Bonus planning</strong>: Choose optimal taxation method</li><li><strong>Job change</strong>: Compare after-tax differences</li></ul><h2>Background</h2><p>The 2019 tax reform raised the threshold to 5,000 CNY/month and introduced special additional deductions. Seven-level progressive rates from 3% to 45%.</p>',
    tool_cn='<div class="form-row"><div class="form-group"><label>税前月工资（元）</label><input type="number" id="salary" value="15000" oninput="calc()"></div><div class="form-group"><label>五险一金（元/月）</label><input type="number" id="insurance" value="2000" oninput="calc()"></div></div><div class="form-row"><div class="form-group"><label>专项附加扣除（元/月）</label><input type="number" id="deduction" value="2000" oninput="calc()"></div><div class="form-group"><label>年终奖（元）</label><input type="number" id="bonus" value="30000" oninput="calc()"></div></div><div class="btn-group"><button class="btn btn-primary" onclick="calc()">🧮 计算</button><button class="btn btn-secondary" onclick="loadExample()">📝 示例</button></div><div class="form-group"><label>计算结果</label><div id="result" style="background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:8px;padding:16px;color:#e2e8f0;font-size:.9rem"></div></div>',
    tool_en='<div class="form-row"><div class="form-group"><label>Pre-tax Monthly Salary (CNY)</label><input type="number" id="salary" value="15000" oninput="calc()"></div><div class="form-group"><label>Social Insurance (CNY/month)</label><input type="number" id="insurance" value="2000" oninput="calc()"></div></div><div class="form-row"><div class="form-group"><label>Special Deductions (CNY/month)</label><input type="number" id="deduction" value="2000" oninput="calc()"></div><div class="form-group"><label>Year-end Bonus (CNY)</label><input type="number" id="bonus" value="30000" oninput="calc()"></div></div><div class="btn-group"><button class="btn btn-primary" onclick="calc()">🧮 Calculate</button><button class="btn btn-secondary" onclick="loadExample()">📝 Example</button></div><div class="form-group"><label>Results</label><div id="result" style="background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:8px;padding:16px;color:#e2e8f0;font-size:.9rem"></div></div>',
    js='var rates=[{min:0,max:36000,rate:.03,deduct:0},{min:36000,max:144000,rate:.10,deduct:2520},{min:144000,max:300000,rate:.20,deduct:16920},{min:300000,max:420000,rate:.25,deduct:31920},{min:420000,max:660000,rate:.30,deduct:52920},{min:660000,max:960000,rate:.35,deduct:85920},{min:960000,max:Infinity,rate:.45,deduct:181920}];function toast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show")},2000)}function calcTax(a){var t=0;for(var i=0;i<rates.length;i++){if(a<=rates[i].min)break;var tx=Math.min(a,rates[i].max)-rates[i].min;t+=tx*rates[i].rate}return t}function calcBonusTax(b){var m=b/12;for(var i=0;i<rates.length;i++){if(m<=rates[i].max){return b*rates[i].rate-rates[i].deduct}}return b*.45-181920}function fmt(n){return n.toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}function calc(){var s=parseFloat(document.getElementById("salary").value)||0;var ins=parseFloat(document.getElementById("insurance").value)||0;var d=parseFloat(document.getElementById("deduction").value)||0;var b=parseFloat(document.getElementById("bonus").value)||0;var mt=s-ins-d-5000;var at=mt*12;var tax=at>0?calcTax(at):0;var monthly=tax/12;var after=s-ins-monthly;var bs=b>0?calcBonusTax(b):0;var bc=b>0?(calcTax(at+b)-tax):0;var best=bs<=bc?"Separate":"Combined";var r=document.getElementById("result");r.innerHTML="<h3 style=\\"color:#22d3ee;margin-bottom:12px\\">Monthly Salary</h3><p>Pre-tax: <strong>"+fmt(s)+"</strong></p><p>Social insurance: <strong>"+fmt(ins)+"</strong></p><p>Special deductions: <strong>"+fmt(d)+"</strong></p><p>Taxable income: <strong>"+fmt(Math.max(0,mt))+"/month</strong></p><p>Monthly tax: <strong style=\\"color:#ef4444\\">"+fmt(Math.max(0,monthly))+"</strong></p><p>After-tax: <strong style=\\"color:#4ade80\\">"+fmt(Math.max(0,after))+"</strong></p><h3 style=\\"color:#22d3ee;margin:16px 0 12px\\">Year-end Bonus</h3><p>Bonus: <strong>"+fmt(b)+"</strong></p><p>Separate tax: <strong style=\\"color:#ef4444\\">"+fmt(bs)+"</strong></p><p>Combined tax: <strong style=\\"color:#ef4444\\">"+fmt(bc)+"</strong></p><p>Recommended: <strong style=\\"color:#4ade80\\">"+best+"</strong></p><p>Savings: <strong style=\\"color:#4ade80\\">"+fmt(Math.abs(bs-bc))+"</strong></p>"}function loadExample(){document.getElementById("salary").value=15000;document.getElementById("insurance").value=2000;document.getElementById("deduction").value=2000;document.getElementById("bonus").value=30000;calc()}calc();',
))

# Tool 4: checklist-maker
TOOLS.append(dict(
    slug='checklist-maker',
    title_cn='清单制作器', title_en='Checklist Maker',
    desc_cn='免费在线清单制作器，创建和管理待办事项、购物清单、检查清单。支持拖拽排序、分类、导出，纯前端本地处理。',
    desc_en='Free online checklist maker. Create and manage to-do lists, shopping lists, and checklists. Drag to reorder, categorize, export. Pure frontend processing.',
    icon='✅',
    cat_cn='办公工具', cat_en='Office Tools', cat_a='office-tools',
    faqs_cn=[
        ('清单数据保存在哪里？', '所有数据保存在浏览器的localStorage中，不会上传到服务器。清除浏览器数据会删除清单。'),
        ('可以创建多个清单吗？', '可以。每个清单独立保存，可以随时切换。'),
        ('支持导出吗？', '支持。可以导出为文本或Markdown格式，方便分享和备份。'),
        ('可以拖拽排序吗？', '支持。通过上下移动按钮调整项目顺序。'),
        ('数据安全吗？', '所有数据完全在浏览器本地运行，不会上传任何数据到服务器。'),
    ],
    faqs_en=[
        ('Where is the data stored?', 'All data is saved in your browser localStorage. Nothing is uploaded to any server.'),
        ('Can I create multiple lists?', 'Yes. Each list is saved independently and you can switch between them.'),
        ('Can I export my lists?', 'Yes. Export as plain text or Markdown format for sharing and backup.'),
        ('Can I reorder items?', 'Yes. Use the up/down buttons to reorder items.'),
        ('Is my data safe?', 'All processing runs locally in your browser. No data is uploaded.'),
    ],
    seo_cn='<h2>清单制作器能做什么？</h2><p>清单制作器是一款免费的在线工具，帮助您创建和管理各种清单：待办事项、购物清单、旅行检查清单等。支持拖拽排序、分类、导出，纯前端本地处理，数据绝不上传。</p><h2>核心功能</h2><ul><li><strong>快速添加</strong>：输入文字按回车即可添加项目</li><li><strong>勾选完成</strong>：点击复选框标记已完成项</li><li><strong>拖拽排序</strong>：上下移动调整项目顺序</li><li><strong>分类管理</strong>：创建多个清单，分类管理</li><li><strong>导出分享</strong>：导出为文本或Markdown</li></ul><h2>使用教程</h2><ol><li><strong>输入项目</strong>：在输入框中输入内容，按回车添加</li><li><strong>勾选完成</strong>：完成的项目点击复选框标记</li><li><strong>调整顺序</strong>：使用上下按钮调整顺序</li><li><strong>导出分享</strong>：点击导出按钮保存清单</li></ol><h2>应用场景</h2><ul><li><strong>待办事项</strong>：每日任务管理</li><li><strong>购物清单</strong>：购物前列出需要买的物品</li><li><strong>旅行准备</strong>：出行前的检查清单</li><li><strong>项目验收</strong>：验收前逐项检查</li></ul><h2>扩展知识</h2><p>清单（Checklist）是一种简单但极其有效的管理工具。航空业使用飞行前检查清单将事故率降低了30%以上。医学界使用手术安全检查清单显著减少了医疗差错。好的清单应该简明扼要、重点突出。</p>',
    seo_en='<h2>What Can the Checklist Maker Do?</h2><p>The checklist maker is a free online tool for creating and managing all kinds of lists: to-do lists, shopping lists, travel checklists, and more. Drag to reorder, categorize, export. Pure frontend processing.</p><h2>Core Features</h2><ul><li><strong>Quick add</strong>: Type and press Enter to add items</li><li><strong>Check off</strong>: Click checkbox to mark completed</li><li><strong>Reorder</strong>: Move items up and down</li><li><strong>Multiple lists</strong>: Create and manage separate lists</li><li><strong>Export</strong>: Save as text or Markdown</li></ul><h2>How to Use</h2><ol><li><strong>Add items</strong>: Type in the input and press Enter</li><li><strong>Check off</strong>: Click checkbox when done</li><li><strong>Reorder</strong>: Use up/down buttons</li><li><strong>Export</strong>: Click export to save your list</li></ol><h2>Use Cases</h2><ul><li><strong>To-do lists</strong>: Daily task management</li><li><strong>Shopping lists</strong>: Plan before shopping</li><li><strong>Travel prep</strong>: Pre-trip checklist</li><li><strong>Project review</strong>: Step-by-step verification</li></ul><h2>Background</h2><p>Checklists are simple but incredibly effective management tools. Aviation uses pre-flight checklists to reduce accident rates by over 30%. Medicine uses surgical safety checklists to significantly reduce medical errors. Good checklists are concise and focused on key items.</p>',
    tool_cn='<div class="form-group"><label>添加项目</label><div style="display:flex;gap:8px"><input type="text" id="newItem" placeholder="输入项目，按回车添加..." onkeydown="if(event.key===\'Enter\')addItem()" style="flex:1;padding:10px 14px;background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:8px;color:#e2e8f0;font-size:.9rem;outline:none"><button class="btn btn-primary" onclick="addItem()">➕ 添加</button></div></div><div class="btn-group"><button class="btn btn-secondary" onclick="clearCompleted()">🗑️ 清除已完成</button><button class="btn btn-success" onclick="exportList()">📋 导出</button><button class="btn btn-secondary" onclick="loadExample()">📝 示例</button></div><div id="checklist" style="background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:8px;padding:12px;min-height:100px"></div><p id="stats" class="info-text" style="margin-top:8px"></p>',
    tool_en='<div class="form-group"><label>Add Item</label><div style="display:flex;gap:8px"><input type="text" id="newItem" placeholder="Type item, press Enter to add..." onkeydown="if(event.key===\'Enter\')addItem()" style="flex:1;padding:10px 14px;background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:8px;color:#e2e8f0;font-size:.9rem;outline:none"><button class="btn btn-primary" onclick="addItem()">➕ Add</button></div></div><div class="btn-group"><button class="btn btn-secondary" onclick="clearCompleted()">🗑️ Clear Done</button><button class="btn btn-success" onclick="exportList()">📋 Export</button><button class="btn btn-secondary" onclick="loadExample()">📝 Example</button></div><div id="checklist" style="background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:8px;padding:12px;min-height:100px"></div><p id="stats" class="info-text" style="margin-top:8px"></p>',
    js='var items=[];function toast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show")},2000)}function save(){localStorage.setItem("checklist_items",JSON.stringify(items))}function load(){var d=localStorage.getItem("checklist_items");if(d)items=JSON.parse(d);render()}function addItem(){var input=document.getElementById("newItem");var text=input.value.trim();if(!text)return;items.push({text:text,done:false,id:Date.now()});input.value="";save();render()}function toggleItem(id){for(var i=0;i<items.length;i++){if(items[i].id===id){items[i].done=!items[i].done;break}}save();render()}function removeItem(id){items=items.filter(function(x){return x.id!==id});save();render()}function moveItem(id,dir){var idx=items.findIndex(function(x){return x.id===id});if(idx<0)return;var ni=idx+dir;if(ni<0||ni>=items.length)return;var t=items[idx];items[idx]=items[ni];items[ni]=t;save();render()}function clearCompleted(){items=items.filter(function(x){return !x.done});save();render();toast("Cleared")}function exportList(){var text=items.map(function(x){return (x.done?"[x]":"[ ]")+" "+x.text}).join("\\n");navigator.clipboard.writeText(text).then(function(){toast("Copied!")})}function loadExample(){items=[{text:"Buy groceries",done:false,id:1},{text:"Clean the house",done:false,id:2},{text:"Call mom",done:true,id:3},{text:"Finish report",done:false,id:4}];save();render()}function render(){var el=document.getElementById("checklist");if(items.length===0){el.innerHTML="<p style=\\"color:#64748b;text-align:center;padding:20px\\">No items yet. Add one above!</p>"}else{el.innerHTML=items.map(function(x){return "<div style=\\"display:flex;align-items:center;gap:8px;padding:8px;border-bottom:1px solid rgba(148,163,184,.1)\\"><input type=\\"checkbox\\" "+(x.done?"checked":"")+" onchange=\\"toggleItem("+x.id+")\\" style=\\"width:18px;height:18px;cursor:pointer\\"><span style=\\"flex:1;"+(x.done?"text-decoration:line-through;color:#64748b":"color:#e2e8f0")+"\\">"+x.text+"</span><button onclick=\\"moveItem("+x.id+",-1)\\" style=\\"background:none;border:none;color:#64748b;cursor:pointer;font-size:.8rem\\">▲</button><button onclick=\\"moveItem("+x.id+",1)\\" style=\\"background:none;border:none;color:#64748b;cursor:pointer;font-size:.8rem\\">▼</button><button onclick=\\"removeItem("+x.id+")\\" style=\\"background:none;border:none;color:#ef4444;cursor:pointer;font-size:.8rem\\">✕</button></div>"}).join("")}var done=items.filter(function(x){return x.done}).length;document.getElementById("stats").textContent=done+"/"+items.length+" completed"}load();',
))

# Tool 5: alphabetical-sorter
TOOLS.append(dict(
    slug='alphabetical-sorter',
    title_cn='字母排序工具', title_en='Alphabetical Sorter',
    desc_cn='免费在线字母排序工具，按字母顺序排列单词、姓名、列表。支持升序降序、去重、自定义分隔符，纯前端本地处理。',
    desc_en='Free online alphabetical sorter. Sort words, names, and lists in alphabetical order. Supports ascending/descending, deduplication, custom separators. Pure frontend processing.',
    icon='🔤',
    cat_cn='文本工具', cat_en='Text Tools', cat_a='text-tools',
    faqs_cn=[
        ('支持中文排序吗？', '支持。中文按拼音排序，英文按字母顺序排序，中英混排自动识别。'),
        ('可以降序排列吗？', '可以。支持升序（A-Z）和降序（Z-A）两种排序方式。'),
        ('可以去除重复项吗？', '可以。勾选"去重"选项即可自动去除重复的行。'),
        ('支持什么分隔符？', '默认按行分隔，也支持逗号、分号、空格等自定义分隔符。'),
        ('数据安全吗？', '所有处理完全在浏览器本地运行，不会上传任何数据到服务器。'),
    ],
    faqs_en=[
        ('Does it support non-English text?', 'Yes. Chinese text is sorted by pinyin, English by alphabetical order. Mixed content is auto-detected.'),
        ('Can I sort in descending order?', 'Yes. Both ascending (A-Z) and descending (Z-A) are supported.'),
        ('Can I remove duplicates?', 'Yes. Check the "Remove duplicates" option to automatically deduplicate.'),
        ('What separators are supported?', 'Default is line-by-line. Also supports comma, semicolon, space, and custom separators.'),
        ('Is my data safe?', 'All processing runs locally in your browser. No data is uploaded.'),
    ],
    seo_cn='<h2>字母排序工具能做什么？</h2><p>字母排序工具是一款免费的在线工具，帮助您快速按字母顺序排列单词、姓名、列表。支持升序降序、去重、自定义分隔符，纯前端本地处理，数据绝不上传。</p><h2>核心功能</h2><ul><li><strong>升序降序</strong>：支持A-Z和Z-A排序</li><li><strong>去重</strong>：一键去除重复项</li><li><strong>多分隔符</strong>：换行、逗号、分号、空格等</li><li><strong>大小写</strong>：支持忽略大小写排序</li><li><strong>编号</strong>：排序后自动编号</li></ul><h2>使用教程</h2><ol><li><strong>输入内容</strong>：在输入框中粘贴或输入列表</li><li><strong>选择选项</strong>：设置排序方向、去重等</li><li><strong>点击排序</strong>：立即查看排序结果</li><li><strong>复制结果</strong>：一键复制到剪贴板</li></ol><h2>应用场景</h2><ul><li><strong>名单整理</strong>：按字母顺序整理姓名列表</li><li><strong>词汇排序</strong>：整理单词表</li><li><strong>数据清洗</strong>：去重和排序</li><li><strong>参考文献</strong>：按作者姓氏排序</li></ul><h2>扩展知识</h2><p>字母排序（Alphabetical Sort）是最基本也是最常用的排序方式。在英文中遵循ASCII/Unicode字符编码顺序，中文排序通常按拼音字母顺序。编程中最常用的排序算法包括快速排序和归并排序，时间复杂度为O(n log n)。</p>',
    seo_en='<h2>What Can the Alphabetical Sorter Do?</h2><p>The alphabetical sorter is a free online tool that helps you quickly sort words, names, and lists in alphabetical order. Supports ascending/descending, deduplication, custom separators. Pure frontend processing.</p><h2>Core Features</h2><ul><li><strong>Ascending/Descending</strong>: A-Z or Z-A sorting</li><li><strong>Deduplication</strong>: Remove duplicates with one click</li><li><strong>Multiple separators</strong>: Newline, comma, semicolon, space</li><li><strong>Case insensitive</strong>: Option to ignore case</li><li><strong>Numbering</strong>: Auto-number sorted results</li></ul><h2>How to Use</h2><ol><li><strong>Enter content</strong>: Paste or type your list</li><li><strong>Select options</strong>: Set sort direction, dedup, etc.</li><li><strong>Click sort</strong>: View sorted results instantly</li><li><strong>Copy result</strong>: One-click copy to clipboard</li></ol><h2>Use Cases</h2><ul><li><strong>Name lists</strong>: Sort names alphabetically</li><li><strong>Vocabulary</strong>: Organize word lists</li><li><strong>Data cleaning</strong>: Deduplicate and sort</li><li><strong>References</strong>: Sort by author surname</li></ul><h2>Background</h2><p>Alphabetical sorting follows ASCII/Unicode character encoding order in English. Chinese sorting typically uses pinyin order. The most common sorting algorithms are quicksort and mergesort, with O(n log n) time complexity.</p>',
    tool_cn='<div class="form-group"><label>输入内容</label><textarea id="input" rows="6" placeholder="每行一个项目，或用逗号/分号分隔..." oninput="sortItems()">banana\napple\ncherry\ndate\nelderberry</textarea></div><div class="form-row"><div class="form-group"><label>排序方向</label><select id="direction" onchange="sortItems()"><option value="asc">升序 (A-Z)</option><option value="desc">降序 (Z-A)</option></select></div><div class="form-group"><label>分隔符</label><select id="separator" onchange="sortItems()"><option value="newline">换行</option><option value="comma">逗号</option><option value="semicolon">分号</option><option value="space">空格</option></select></div></div><div class="form-row"><div class="form-group"><label><input type="checkbox" id="dedup" onchange="sortItems()" checked> 去除重复项</label></div><div class="form-group"><label><input type="checkbox" id="ignoreCase" onchange="sortItems()" checked> 忽略大小写</label></div><div class="form-group"><label><input type="checkbox" id="addNumbers" onchange="sortItems()"> 添加编号</label></div></div><div class="btn-group"><button class="btn btn-primary" onclick="sortItems()">🔤 排序</button><button class="btn btn-success" onclick="copyResult()">📋 复制</button><button class="btn btn-secondary" onclick="loadExample()">📝 示例</button></div><div class="form-group"><label>排序结果</label><textarea id="output" rows="6" readonly style="font-family:monospace;background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:8px;padding:12px;color:#22d3ee;font-size:.85rem;width:100%;resize:vertical"></textarea></div>',
    tool_en='<div class="form-group"><label>Input</label><textarea id="input" rows="6" placeholder="One item per line, or comma/semicolon separated..." oninput="sortItems()">banana\napple\ncherry\ndate\nelderberry</textarea></div><div class="form-row"><div class="form-group"><label>Sort Direction</label><select id="direction" onchange="sortItems()"><option value="asc">Ascending (A-Z)</option><option value="desc">Descending (Z-A)</option></select></div><div class="form-group"><label>Separator</label><select id="separator" onchange="sortItems()"><option value="newline">Newline</option><option value="comma">Comma</option><option value="semicolon">Semicolon</option><option value="space">Space</option></select></div></div><div class="form-row"><div class="form-group"><label><input type="checkbox" id="dedup" onchange="sortItems()" checked> Remove duplicates</label></div><div class="form-group"><label><input type="checkbox" id="ignoreCase" onchange="sortItems()" checked> Ignore case</label></div><div class="form-group"><label><input type="checkbox" id="addNumbers" onchange="sortItems()"> Add numbering</label></div></div><div class="btn-group"><button class="btn btn-primary" onclick="sortItems()">🔤 Sort</button><button class="btn btn-success" onclick="copyResult()">📋 Copy</button><button class="btn btn-secondary" onclick="loadExample()">📝 Example</button></div><div class="form-group"><label>Result</label><textarea id="output" rows="6" readonly style="font-family:monospace;background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:8px;padding:12px;color:#22d3ee;font-size:.85rem;width:100%;resize:vertical"></textarea></div>',
    js='function toast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show")},2000)}function sortItems(){var text=document.getElementById("input").value;if(!text.trim()){document.getElementById("output").value="";return}var sep=document.getElementById("separator").value;var sepChar=sep==="comma"?",":sep==="semicolon"?";":sep==="space"?" ":"\\n";var items=text.split(sepChar).map(function(s){return s.trim()}).filter(function(s){return s});var dedup=document.getElementById("dedup").checked;var ignoreCase=document.getElementById("ignoreCase").checked;var direction=document.getElementById("direction").value;var addNum=document.getElementById("addNumbers").checked;if(dedup){var seen={};items=items.filter(function(s){var k=ignoreCase?s.toLowerCase():s;if(seen[k])return false;seen[k]=true;return true})}items.sort(function(a,b){var ca=ignoreCase?a.toLowerCase():a;var cb=ignoreCase?b.toLowerCase():b;return direction==="asc"?ca.localeCompare(cb):cb.localeCompare(ca)});if(addNum){items=items.map(function(s,i){return(i+1)+". "+s})}document.getElementById("output").value=items.join("\\n")}function copyResult(){var o=document.getElementById("output");if(!o.value)return;navigator.clipboard.writeText(o.value).then(function(){toast("Copied!")})}function loadExample(){document.getElementById("input").value="banana\\napple\\ncherry\\ndate\\nelderberry\\nfig\\ngrape";sortItems()}sortItems();',
))

if __name__ == '__main__':
    print(f"Defined {len(TOOLS)} tools total (including {TOOLS.__len__()} from this file)")
    for t in TOOLS:
        print(f"  - {t['slug']}: {t['title_cn']} / {t['title_en']}")
