#!/usr/bin/env python3
"""批量翻译5个工具页面从CN到EN"""
import os, re

SITE = '/home/chison/tools-site'

TRANSLATIONS = {
    'biweekly-payment-calculator': {
        'lang="zh-CN"': 'lang="en"',
        '双周还款计算器': 'Biweekly Payment Calculator',
        '免费双周还款计算器，比较双周还款与月供的利息节省。输入贷款金额、利率、期限，查看提前还清时间和节省利息。适合房贷加速还款规划。': 'Free biweekly payment calculator. Compare biweekly vs monthly payments to see interest savings and early payoff. Input loan amount, rate, and term to calculate savings.',
        '免费双周还款计算器，比较双周还款 vs 月供的利息差和提前还清时间。每两周还一半月供，每年多还1次，大幅节省利息！': 'Free biweekly payment calculator. Compare biweekly vs monthly payments and see how paying half your monthly every 2 weeks saves interest and pays off your loan faster!',
        '关于双周还款计算器': 'About Biweekly Payment Calculator',
        '双周还款（Biweekly Payment）是将月供分成两半，每两周还一次。因为一年有52周=26次双周=13个月供，相当于每年多还一次月供的本金，可大幅减少利息并缩短还款期限。适合有稳定双周收入的工薪族加速还贷。': 'Biweekly payments split your monthly payment in half and pay every 2 weeks. Since a year has 52 weeks = 26 biweekly periods = 13 monthly equivalents, you make one extra payment per year toward principal, significantly reducing interest and loan term. Ideal for salaried workers with biweekly paychecks.',
        '贷款参数': 'Loan Parameters',
        '贷款金额 (元)': 'Loan Amount ($)',
        '年利率 (%)': 'Annual Rate (%)',
        '贷款期限 (年)': 'Loan Term (years)',
        '计算': 'Calculate',
        '复制结果': 'Copy Results',
        '清空': 'Clear',
        '还款对比': 'Payment Comparison',
        '月供金额': 'Monthly Payment',
        '双周还款额': 'Biweekly Payment',
        '原总利息': 'Original Total Interest',
        '双周总利息': 'Biweekly Total Interest',
        '节省利息': 'Interest Saved',
        '提前还清': 'Early Payoff',
        '个月': 'months',
        '月供方案': 'Monthly Plan',
        '双周还款方案': 'Biweekly Plan',
        '差异': 'Difference',
        '每次还款额': 'Per Payment',
        '半额': 'Half Amount',
        '年还款次数': 'Payments/Year',
        '年还款总额': 'Annual Total',
        '还款总期': 'Total Term',
        '总利息': 'Total Interest',
        '已复制到剪贴板': 'Copied to clipboard',
        '复制失败': 'Copy failed',
        '已清空': 'Cleared',
        '请输入有效参数': 'Please enter valid parameters',
        '无需注册 · 数据绝不上传服务器': 'No registration · Data never leaves your device',
        '零依赖·可离线使用': 'Zero dependencies · Works offline',
        '首页': 'Home',
        '工具': 'Tools',
        'English': '中文',
        '中文': 'English',
        'active': 'active',
        'en/biweekly-payment-calculator/': '../biweekly-payment-calculator/',
        '../en/biweekly-payment-calculator/': 'index.html',
        '"zh"': '"en"',
        '"en"': '"en"',
    },
    'extra-payment-calculator': {
        'lang="zh-CN"': 'lang="en"',
        '额外还款计算器': 'Extra Payment Calculator',
        '免费额外还款计算器，计算在月供基础上额外多还本金可节省的利息和缩短的还款期限。支持按月/按年/一次性额外还款。适合房贷、车贷提前还款规划。': 'Free extra payment calculator. See how making additional principal payments on top of your regular monthly payment saves interest and shortens your loan term. Supports monthly, yearly, or one-time extra payments.',
        '免费额外还款计算器，在月供基础上每期多还一些本金，看看能省多少利息、提前多久还清。支持按月、按年或一次性额外还款。': 'Free extra payment calculator. Add extra principal to your monthly payment and see how much interest you save and how much earlier you pay off your loan. Supports monthly, yearly, or one-time extra payments.',
        '关于额外还款计算器': 'About Extra Payment Calculator',
        '额外还款（Extra Payment）是在每月应还金额基础上，自愿多还一部分本金。即使是小额额外还款，由于复利效应，也能大幅减少总利息并缩短还款周期。常见方式包括：每月固定多还、年终奖一次性多还、或一次性大额还款。': 'Extra payments are voluntary additional principal payments on top of your regular monthly amount. Even small extra payments can significantly reduce total interest and shorten your loan term due to compounding effects. Common approaches include fixed monthly extras, annual bonus lump sums, or one-time large payments.',
        '贷款参数': 'Loan Parameters',
        '贷款金额 (元)': 'Loan Amount ($)',
        '年利率 (%)': 'Annual Rate (%)',
        '贷款期限 (年)': 'Loan Term (years)',
        '额外还款方式': 'Extra Payment Mode',
        '每月额外还': 'Monthly Extra',
        '每年额外还': 'Yearly Extra',
        '一次性额外还': 'One-time Extra',
        '额外还款金额 (元)': 'Extra Payment Amount ($)',
        '计算': 'Calculate',
        '复制结果': 'Copy Results',
        '清空': 'Clear',
        '还款对比': 'Payment Comparison',
        '正常月供': 'Regular Monthly',
        '正常总利息': 'Original Total Interest',
        '加速总利息': 'Accelerated Total Interest',
        '节省利息': 'Interest Saved',
        '原期限': 'Original Term',
        '加速后期限': 'Accelerated Term',
        '提前': 'Early',
        '年': 'yr',
        '个月': 'mo',
        '还清，节省': 'payoff, saving',
        '利息': 'interest',
        '已复制': 'Copied',
        '复制失败': 'Copy failed',
        '已清空': 'Cleared',
        '请输入有效参数': 'Please enter valid parameters',
        '无需注册 · 数据绝不上传服务器': 'No registration · Data never leaves your device',
        '零依赖·可离线使用': 'Zero dependencies · Works offline',
        '首页': 'Home',
        '工具': 'Tools',
        '每月额外还 (元)': 'Monthly Extra ($)',
        '每年额外还 (元)': 'Yearly Extra ($)',
        '一次性额外还 (元)': 'One-time Extra ($)',
    },
    'balloon-payment-calculator': {
        'lang="zh-CN"': 'lang="en"',
        '气球贷款计算器': 'Balloon Payment Calculator',
        '免费气球贷款计算器，计算期末一次性大额还款（Balloon Payment）的月供和总成本。适合商业贷款、过桥贷款、车贷尾款规划。': 'Free balloon payment calculator. Calculate monthly payments and total cost with a large end-of-term balloon payment. Ideal for business loans, bridge loans, and car loan residual planning.',
        '免费气球贷款计算器。气球贷款前期月供较低，期末需一次性还清大额尾款。适合商业贷款、过桥贷款、车贷尾款规划。': 'Free balloon payment calculator. Balloon loans have lower monthly payments but require a large lump sum at the end. Ideal for business loans, bridge loans, and car residual planning.',
        '关于气球贷款计算器': 'About Balloon Payment Calculator',
        '气球贷款（Balloon Loan）是一种前期月供较低、期末需一次性偿还大额尾款的贷款方式。常见于商业贷款、过桥贷款、车贷尾款等场景。虽然前期压力小，但期末尾款压力大，需提前规划还款来源。': 'A balloon loan features lower monthly payments with a large lump sum due at maturity. Common in commercial lending, bridge loans, and car financing with residuals. While monthly pressure is lower, the balloon payment at the end requires advance planning.',
        '贷款参数': 'Loan Parameters',
        '贷款金额 (元)': 'Loan Amount ($)',
        '年利率 (%)': 'Annual Rate (%)',
        '贷款期限 (月)': 'Loan Term (months)',
        '气球尾款比例 (%)': 'Balloon Payment (%)',
        '期末一次性还款占本金比例': 'Balloon as % of principal',
        '计算': 'Calculate',
        '复制结果': 'Copy Results',
        '清空': 'Clear',
        '计算结果': 'Results',
        '月供金额': 'Monthly Payment',
        '期末尾款': 'Balloon Payment',
        '总还款额': 'Total Paid',
        '总利息': 'Total Interest',
        '标准月供(对比)': 'Standard Monthly (vs.)',
        '月供减少': 'Monthly Savings',
        '注意：第': 'Note: At month ',
        '个月需一次性支付尾款': ', a lump sum of ',
        '尾款占总还款': 'Balloon is ',
        '已复制': 'Copied',
        '复制失败': 'Copy failed',
        '已清空': 'Cleared',
        '请输入有效参数': 'Please enter valid parameters',
        '无需注册 · 数据绝不上传服务器': 'No registration · Data never leaves your device',
        '零依赖·可离线使用': 'Zero dependencies · Works offline',
        '首页': 'Home',
        '工具': 'Tools',
    },
    'arm-vs-fixed-calculator': {
        'lang="zh-CN"': 'lang="en"',
        '浮动vs固定利率计算器': 'ARM vs Fixed Rate Calculator',
        '免费浮动vs固定利率对比计算器，模拟ARM可调利率贷款与固定利率贷款在不同利率场景下的总成本对比。帮助选择最优房贷方案。': 'Free ARM vs fixed rate comparison calculator. Simulate adjustable-rate mortgages vs fixed-rate loans under different rate scenarios to compare total costs.',
        '免费浮动利率(ARM)vs固定利率对比计算器。模拟可调利率贷款前N年固定期后的利率调整，与全程固定利率对比总成本和月供变化。': 'Free ARM vs fixed rate comparison calculator. Simulate an adjustable-rate mortgage with an initial fixed period followed by rate adjustment, and compare total costs and payment changes against a fixed-rate loan.',
        '关于浮动vs固定利率计算器': 'About ARM vs Fixed Rate Calculator',
        'ARM（可调利率抵押贷款）前N年享有较低固定利率，之后按市场利率调整。本计算器模拟ARM在固定期结束、利率上调后的月供跳涨和总成本变化，帮助您判断ARM是否真的划算。': 'An ARM (Adjustable-Rate Mortgage) offers a lower fixed rate for the first N years, then adjusts to market rates. This calculator simulates the payment jump and total cost change when the fixed period ends and rates rise, helping you decide if an ARM is worth it.',
        '贷款参数': 'Loan Parameters',
        '贷款金额 (元)': 'Loan Amount ($)',
        '总贷款期限 (年)': 'Total Loan Term (years)',
        '固定利率方案': 'Fixed Rate Plan',
        '固定年利率 (%)': 'Fixed Annual Rate (%)',
        '浮动利率(ARM)方案': 'ARM Plan',
        '固定期利率 (%)': 'Initial Fixed Rate (%)',
        '固定期 (月)': 'Fixed Period (months)',
        '如5年ARM=60个月': 'e.g. 5/1 ARM = 60 months',
        '调整后利率 (%)': 'Adjusted Rate (%)',
        '计算对比': 'Compare',
        '复制结果': 'Copy Results',
        '清空': 'Clear',
        '方案对比': 'Plan Comparison',
        '固定利率': 'Fixed Rate',
        '浮动ARM': 'ARM',
        '前期月供': 'Initial Monthly',
        '后期月供': 'Later Monthly',
        '总还款额': 'Total Paid',
        '总利息': 'Total Interest',
        '差异': 'Diff',
        'ARM多付': 'ARM pays more',
        'ARM少付': 'ARM pays less',
        '固定月供': 'Fixed Payment',
        'ARM起始月供': 'ARM Start Payment',
        'ARM调整后月供': 'ARM Adjusted Payment',
        '已复制': 'Copied',
        '复制失败': 'Copy failed',
        '已清空': 'Cleared',
        '请输入有效参数': 'Please enter valid parameters',
        '无需注册 · 数据绝不上传服务器': 'No registration · Data never leaves your device',
        '零依赖·可离线使用': 'Zero dependencies · Works offline',
        '首页': 'Home',
        '工具': 'Tools',
    },
    'home-equity-calculator': {
        'lang="zh-CN"': 'lang="en"',
        '房屋净值计算器': 'Home Equity Calculator',
        '免费房屋净值计算器，计算房产净值（房屋价值-剩余贷款）和可贷额度。支持LTV/CLTV计算，适合房屋净值贷款和HELOC额度评估。': 'Free home equity calculator. Calculate your home equity (home value minus loan balance) and borrowing capacity. Supports LTV/CLTV calculations for home equity loans and HELOC assessment.',
        '免费房屋净值计算器，输入房屋估值和剩余贷款，计算可动用净值。支持LTV/CLTV计算，适合房屋净值贷款和HELOC额度评估。': 'Free home equity calculator. Enter your home value and loan balance to calculate available equity. Supports LTV/CLTV for home equity loans and HELOC assessment.',
        '关于房屋净值计算器': 'About Home Equity Calculator',
        '房屋净值（Home Equity）= 房屋当前估值 - 剩余贷款余额。银行通常允许借到房屋价值的80%（LTV 80%），减去已有抵押。本计算器帮您快速评估可动用净值，适合规划房屋净值贷款（Home Equity Loan）或HELOC。': 'Home Equity = Current Home Value - Remaining Loan Balance. Banks typically allow borrowing up to 80% of home value (LTV 80%), minus existing liens. This calculator helps you quickly assess available equity for home equity loans or HELOCs.',
        '房屋信息': 'Home Information',
        '房屋当前估值 (元)': 'Home Value ($)',
        '剩余贷款余额 (元)': 'Loan Balance ($)',
        '最高LTV比例 (%)': 'Max LTV Ratio (%)',
        '通常银行允许最高80%': 'Typically banks allow up to 80%',
        '已有第二抵押 (元)': 'Existing 2nd Lien ($)',
        '如有HELOC或其他抵押': 'If you have a HELOC or other lien',
        '计算': 'Calculate',
        '复制结果': 'Copy Results',
        '清空': 'Clear',
        '净值分析': 'Equity Analysis',
        '房屋净值': 'Home Equity',
        '净值占比': 'Equity %',
        '当前LTV': 'Current LTV',
        '最高可贷额度': 'Max Borrowable',
        '净值占比': 'Equity Ratio',
        '贷款占比': 'Loan Ratio',
        '您可申请最高': 'You can borrow up to',
        '的房屋净值贷款或HELOC': 'via home equity loan or HELOC',
        '当前LTV已达': 'Current LTV is at ',
        '，暂无可贷额度': ', no borrowing capacity available',
        '已复制': 'Copied',
        '复制失败': 'Copy failed',
        '已清空': 'Cleared',
        '请输入有效参数': 'Please enter valid parameters',
        '无需注册 · 数据绝不上传服务器': 'No registration · Data never leaves your device',
        '零依赖·可离线使用': 'Zero dependencies · Works offline',
        '首页': 'Home',
        '工具': 'Tools',
    },
}

for tool_name, translations in TRANSLATIONS.items():
    path = os.path.join(SITE, 'en', tool_name, 'index.html')
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for old, new in translations.items():
        content = content.replace(old, new)
    
    # Fix canonical URL
    content = content.replace('https://free-toolbase.com/' + tool_name + '/', 'https://free-toolbase.com/en/' + tool_name + '/')
    
    # Fix hreflang
    content = content.replace('hreflang="zh" href="https://free-toolbase.com/' + tool_name + '/"', 'hreflang="en" href="https://free-toolbase.com/en/' + tool_name + '/"')
    content = content.replace('hreflang="en" href="https://free-toolbase.com/en/' + tool_name + '/"', 'hreflang="en" href="https://free-toolbase.com/en/' + tool_name + '/"')
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Translated: {tool_name}")
