#!/usr/bin/env python3
"""生成完整英文版 - 复制中文版HTML并替换核心UI文本"""
import re, os

tool_configs = {
    "spin-the-wheel": [
        (r'lang="zh-CN"', 'lang="en"'),
        (r'<title>.*?</title>', '<title>Spin the Wheel - Online Prize & Decision Wheel | Free ToolBase</title>'),
        (r'<meta name="description" content="[^"]*"', '<meta name="description" content="Free online spinning wheel tool. Customize options and colors, randomly spin to pick results. Perfect for raffles, decisions, and games. 100% browser-based."'),
        (r'<meta name="keywords" content="[^"]*"', '<meta name="keywords" content="spin the wheel, online wheel, lucky wheel, decision wheel, random wheel, prize wheel"'),
        (r'<meta property="og:title" content="[^"]*"', '<meta property="og:title" content="Spin the Wheel - Online Prize & Decision Wheel | Free ToolBase"'),
        (r'<meta property="og:description" content="[^"]*"', '<meta property="og:description" content="Free online spinning wheel tool. Customize options and colors, randomly spin to pick results."'),
        (r'content="https://free-toolbase.com/spin-the-wheel/"', 'content="https://free-toolbase.com/en/spin-the-wheel/"'),
        (r'href="../en/spin-the-wheel/"', 'href="../../spin-the-wheel/"'),
        (r'hreflang="zh".*?/>', 'hreflang="en" href="https://free-toolbase.com/en/spin-the-wheel/">'),
        (r'hreflang="en".*?/>', 'hreflang="zh" href="https://free-toolbase.com/spin-the-wheel/">'),
        (r'hreflang="x-default".*?/>', 'hreflang="x-default" href="https://free-toolbase.com/en/spin-the-wheel/">'),
        (r'"name":"幸运转盘"', '"name":"Spin the Wheel"'),
        (r'"免费在线幸运转盘[^"]*"', '"Free online spinning wheel tool. Customize options and colors, randomly spin to pick results."'),
        (r'<h1>[^<]*</h1>', '<h1>🎡 Spin the Wheel</h1>'),
        (r'<p class="nav-back">.*?</p>', '<p class="nav-back"><a href="../../index.html">Home</a> &rsaquo; <a href="../../index.html#tools">Tools</a> &rsaquo; Spin the Wheel</p>'),
        (r'<a href="index.html" class="active">[^<]*</a>', '<a href="../../spin-the-wheel/">中文</a>'),
        (r'<a href="\.\./en/spin-the-wheel/">[^<]*</a>', '<a href="index.html" class="active">EN</a>'),
        (r'<p>免费在线幸运转盘[^<]*</p>', '<p>Free online spinning wheel. Customize option text and colors, randomly spin to pick results. All processing is local, no data uploaded.</p>'),
        ('零依赖·可离线使用', 'Zero Dependencies · Works Offline'),
        ('编辑选项（每行一个）', 'Edit Options (one per line)'),
        ('是/否', 'Yes/No'),
        ('晚餐选择', 'Dinner'),
        ('抽奖', 'Raffle'),
        ('颜色', 'Colors'),
        ('骰子1-6', 'Dice 1-6'),
        ('🔄 更新转盘', '🔄 Update Wheel'),
        ('🎉 结果：', '🎉 Result: '),
        ('使用说明', 'How to Use'),
        ('应用场景', 'Use Cases'),
        (r'<p><strong>编辑选项：</strong>[^<]*</p>', '<p><strong>Edit Options:</strong> Enter options in the right panel, one per line. Supports 2-20 options.</p>'),
        (r'<p><strong>旋转：</strong>[^<]*</p>', '<p><strong>Spin:</strong> Click the "Spin" button for a random result with realistic animation.</p>'),
        (r'<p><strong>预设：</strong>[^<]*</p>', '<p><strong>Presets:</strong> Click preset buttons to quickly load common options (Yes/No, Dinner, Raffle, Colors, Dice).</p>'),
        (r'<p><strong>原理：</strong>[^<]*</p>', '<p><strong>How it works:</strong> Canvas-based wheel with random angle and easing animation for authentic spinning feel.</p>'),
        (r'<p><strong>日常决策：</strong>[^<]*</p>', '<p><strong>Daily Decisions:</strong> "What\'s for dinner?" Let the wheel decide!</p>'),
        (r'<p><strong>课堂互动：</strong>[^<]*</p>', '<p><strong>Classroom:</strong> Teachers randomly pick students for questions - fair and fun.</p>'),
        (r'<p><strong>活动抽奖：</strong>[^<]*</p>', '<p><strong>Events:</strong> Lucky draws at parties, adding ceremony and excitement.</p>'),
        (r'<p><strong>游戏娱乐：</strong>[^<]*</p>', '<p><strong>Games:</strong> Board game actions, truth or dare random selection.</p>'),
        ('幸运转盘 | 无需注册 · 数据绝不上传服务器', 'Spin the Wheel | No Registration · Data Never Uploads'),
        ('至少需要2个选项', 'At least 2 options required'),
        (r'href="\.\./privacy/"', 'href="../../privacy/"'),
        (r'href="\.\./terms/"', 'href="../../terms/"'),
        (r'href="\.\./about/"', 'href="../../about/"'),
        (r'href="\.\./index.html"', 'href="../../index.html"'),
        ('首页', 'Home'),
        ('全部工具', 'All Tools'),
        ('联系我们', 'Contact'),
        ('隐私政策', 'Privacy'),
        ('服务条款', 'Terms'),
        ('关于我们', 'About'),
        (r'<a href="\.\./en/spin-the-wheel/">EN</a>', '<a href="../../spin-the-wheel/">中文</a>'),
        ('问题反馈', 'Feedback'),
        (r'\u201c吃什么', '"What to eat'),
    ],
    "random-group-generator": [
        (r'lang="zh-CN"', 'lang="en"'),
        (r'<title>.*?</title>', '<title>Random Group Generator - Online Team Splitter | Free ToolBase</title>'),
        (r'<meta name="description" content="[^"]*"', '<meta name="description" content="Free online random group generator. Split names into groups evenly or randomly. Perfect for classrooms, team building, and lottery draws. Pure frontend."'),
        (r'<meta name="keywords" content="[^"]*"', '<meta name="keywords" content="random group generator, random groups, team generator, group splitter, random team maker, classroom groups"'),
        (r'<meta property="og:title" content="[^"]*"', '<meta property="og:title" content="Random Group Generator - Online Team Splitter | Free ToolBase"'),
        (r'<meta property="og:description" content="[^"]*"', '<meta property="og:description" content="Free online random group generator. Split names into groups evenly or randomly."'),
        (r'content="https://free-toolbase.com/random-group-generator/"', 'content="https://free-toolbase.com/en/random-group-generator/"'),
        (r'href="\.\./en/random-group-generator/"', 'href="../../random-group-generator/"'),
        (r'hreflang="zh".*?/>', 'hreflang="en" href="https://free-toolbase.com/en/random-group-generator/">'),
        (r'hreflang="en".*?/>', 'hreflang="zh" href="https://free-toolbase.com/random-group-generator/">'),
        (r'hreflang="x-default".*?/>', 'hreflang="x-default" href="https://free-toolbase.com/en/random-group-generator/">'),
        (r'"name":"随机分组生成器"', '"name":"Random Group Generator"'),
        (r'"免费在线随机分组工具[^"]*"', '"Free online random group generator. Split names into groups evenly or randomly."'),
        (r'<h1>[^<]*</h1>', '<h1>👥 Random Group Generator</h1>'),
        (r'<p class="nav-back">.*?</p>', '<p class="nav-back"><a href="../../index.html">Home</a> &rsaquo; <a href="../../index.html#tools">Tools</a> &rsaquo; Random Group Generator</p>'),
        (r'<a href="index.html" class="active">[^<]*</a>', '<a href="../../random-group-generator/">中文</a>'),
        (r'<a href="\.\./en/random-group-generator/">[^<]*</a>', '<a href="index.html" class="active">EN</a>'),
        (r'<p>免费在线随机分组工具[^<]*</p>', '<p>Free online random group generator. Split names into groups with even distribution. All local processing.</p>'),
        ('零依赖·可离线使用', 'Zero Dependencies · Works Offline'),
        ('📋 输入名单（每行一个）', '📋 Enter Names (one per line)'),
        ('组数：', 'Groups: '),
        ('🎲 随机分组', '🎲 Generate Groups'),
        ('🔀 重新洗牌', '🔀 Reshuffle'),
        ('📊 分组结果', '📊 Result'),
        ('输入名单并设置组数后，点击"随机分组"查看结果', 'Enter names and set group count, then click "Generate Groups"'),
        ('📋 复制结果', '📋 Copy Result'),
        ('第', 'Group '),
        ('人)', ' people)'),
        ('使用说明', 'How to Use'),
        ('应用场景', 'Use Cases'),
        (r'<p><strong>输入名单：</strong>[^<]*</p>', '<p><strong>Enter Names:</strong> Type participant names in the left panel, one name per line. Supports all languages.</p>'),
        (r'<p><strong>设置组数：</strong>[^<]*</p>', '<p><strong>Set Groups:</strong> Specify the number of groups (2-50).</p>'),
        (r'<p><strong>随机分组：</strong>[^<]*</p>', '<p><strong>Generate:</strong> Click "Generate Groups" to randomly shuffle and evenly distribute names.</p>'),
        (r'<p><strong>重新洗牌：</strong>[^<]*</p>', '<p><strong>Reshuffle:</strong> Not satisfied? Click "Reshuffle" for a new random distribution.</p>'),
        (r'<p><strong>课堂分组：</strong>[^<]*</p>', '<p><strong>Classroom:</strong> Teachers quickly split students into discussion groups - fair and random.</p>'),
        (r'<p><strong>团建活动：</strong>[^<]*</p>', '<p><strong>Team Building:</strong> Randomly divide colleagues into competition teams for added fun.</p>'),
        (r'<p><strong>随机抽签：</strong>[^<]*</p>', '<p><strong>Lottery Draw:</strong> Randomly pick people from a list, like a lucky draw.</p>'),
        (r'<p><strong>实验室分组：</strong>[^<]*</p>', '<p><strong>Experiments:</strong> Randomly assign participants to experiment and control groups.</p>'),
        ('随机分组生成器 | 无需注册 · 数据绝不上传服务器', 'Random Group Generator | No Registration · Data Never Uploads'),
        ('至少需要2个名字', 'At least 2 names required'),
        ('请先点击随机分组', 'Please generate groups first'),
        ('已复制分组结果', 'Group result copied'),
        (r'href="\.\./privacy/"', 'href="../../privacy/"'),
        (r'href="\.\./terms/"', 'href="../../terms/"'),
        (r'href="\.\./about/"', 'href="../../about/"'),
        (r'href="\.\./index.html"', 'href="../../index.html"'),
        ('首页', 'Home'),
        ('全部工具', 'All Tools'),
        ('联系我们', 'Contact'),
        ('隐私政策', 'Privacy'),
        ('服务条款', 'Terms'),
        ('关于我们', 'About'),
        (r'<a href="\.\./en/random-group-generator/">EN</a>', '<a href="../../random-group-generator/">中文</a>'),
        ('问题反馈', 'Feedback'),
    ],
    "canvas-painter": [
        (r'lang="zh-CN"', 'lang="en"'),
        (r'<title>.*?</title>', '<title>Online Canvas Painter - Free Drawing & Sketch Tool | Free ToolBase</title>'),
        (r'<meta name="description" content="[^"]*"', '<meta name="description" content="Free online canvas drawing tool with pen, eraser, color picker, adjustable brush size, undo/redo, and PNG export. Pure Canvas-based, no download needed."'),
        (r'<meta name="keywords" content="[^"]*"', '<meta name="keywords" content="canvas painter, online drawing, sketch tool, doodle board, canvas drawing, paint online"'),
        (r'<meta property="og:title" content="[^"]*"', '<meta property="og:title" content="Online Canvas Painter - Free Drawing & Sketch Tool | Free ToolBase"'),
        (r'<meta property="og:description" content="[^"]*"', '<meta property="og:description" content="Free online canvas drawing tool with pen, eraser, color picker, adjustable brush size, undo/redo, and PNG export."'),
        (r'content="https://free-toolbase.com/canvas-painter/"', 'content="https://free-toolbase.com/en/canvas-painter/"'),
        (r'href="\.\./en/canvas-painter/"', 'href="../../canvas-painter/"'),
        (r'hreflang="zh".*?/>', 'hreflang="en" href="https://free-toolbase.com/en/canvas-painter/">'),
        (r'hreflang="en".*?/>', 'hreflang="zh" href="https://free-toolbase.com/canvas-painter/">'),
        (r'hreflang="x-default".*?/>', 'hreflang="x-default" href="https://free-toolbase.com/en/canvas-painter/">'),
        (r'"name":"在线画布绘画"', '"name":"Online Canvas Painter"'),
        (r'"免费在线画布绘画工具[^"]*"', '"Free online canvas drawing tool with pen, eraser, color picker, PNG export."'),
        (r'<h1>[^<]*</h1>', '<h1>🎨 Online Canvas Painter</h1>'),
        (r'<p class="nav-back">.*?</p>', '<p class="nav-back"><a href="../../index.html">Home</a> &rsaquo; <a href="../../index.html#tools">Tools</a> &rsaquo; Online Canvas Painter</p>'),
        (r'<a href="index.html" class="active">[^<]*</a>', '<a href="../../canvas-painter/">中文</a>'),
        (r'<a href="\.\./en/canvas-painter/">[^<]*</a>', '<a href="index.html" class="active">EN</a>'),
        (r'<p>免费在线画布绘画工具[^<]*</p>', '<p>Free online canvas drawing tool with pen and eraser, adjustable color and brush size, undo/redo, one-click PNG export. Pure Canvas-based, no download needed.</p>'),
        ('零依赖·可离线使用', 'Zero Dependencies · Works Offline'),
        ('✏️ 画笔', '✏️ Pen'),
        ('🧹 橡皮', '🧹 Eraser'),
        ('粗细', 'Size'),
        ('↩ 撤销', '↩ Undo'),
        ('↪ 重做', '↪ Redo'),
        ('🗑 清空', '🗑 Clear'),
        ('📥 下载PNG', '📥 Download PNG'),
        ('使用说明', 'How to Use'),
        ('应用场景', 'Use Cases'),
        (r'<p><strong>画笔模式：</strong>[^<]*</p>', '<p><strong>Pen Mode:</strong> Select "Pen" tool, click and drag on the canvas to draw. Touch screen supported.</p>'),
        (r'<p><strong>橡皮模式：</strong>[^<]*</p>', '<p><strong>Eraser Mode:</strong> Select "Eraser" to remove unwanted parts. Eraser size is adjustable.</p>'),
        (r'<p><strong>颜色选择：</strong>[^<]*</p>', '<p><strong>Colors & Size:</strong> Use the color picker for any color, adjust brush size (1-50px).</p>'),
        (r'<p><strong>撤销/重做：</strong>[^<]*</p>', '<p><strong>Undo/Redo:</strong> Multi-step undo (Ctrl+Z) and redo (Ctrl+Y) for easy corrections.</p>'),
        (r'<p><strong>导出：</strong>[^<]*</p>', '<p><strong>Export:</strong> Click "Download PNG" to save your artwork as a PNG image.</p>'),
        (r'<p><strong>草图绘制：</strong>[^<]*</p>', '<p><strong>Sketching:</strong> Quick flowcharts, mind maps, design sketches.</p>'),
        (r'<p><strong>在线教学：</strong>[^<]*</p>', '<p><strong>Teaching:</strong> Teachers demonstrate problem-solving, students take notes.</p>'),
        (r'<p><strong>创意涂鸦：</strong>[^<]*</p>', '<p><strong>Doodling:</strong> Creative doodling to relax and express creativity.</p>'),
        (r'<p><strong>标注说明：</strong>[^<]*</p>', '<p><strong>Annotations:</strong> Mark up screenshots with notes and highlights.</p>'),
        ('在线画布绘画 | 无需注册 · 数据绝不上传服务器', 'Online Canvas Painter | No Registration · Data Never Uploads'),
        ('画布已清空', 'Canvas cleared'),
        ('已下载PNG图片', 'PNG image downloaded'),
        (r'href="\.\./privacy/"', 'href="../../privacy/"'),
        (r'href="\.\./terms/"', 'href="../../terms/"'),
        (r'href="\.\./about/"', 'href="../../about/"'),
        (r'href="\.\./index.html"', 'href="../../index.html"'),
        ('首页', 'Home'),
        ('全部工具', 'All Tools'),
        ('联系我们', 'Contact'),
        ('隐私政策', 'Privacy'),
        ('服务条款', 'Terms'),
        ('关于我们', 'About'),
        (r'<a href="\.\./en/canvas-painter/">EN</a>', '<a href="../../canvas-painter/">中文</a>'),
        ('问题反馈', 'Feedback'),
    ],
    "emotion-wheel": [
        (r'lang="zh-CN"', 'lang="en"'),
        (r'<title>.*?</title>', '<title>Emotion Wheel - Online Emotion Recognition Tool | Free ToolBase</title>'),
        (r'<meta name="description" content="[^"]*"', '<meta name="description" content="Free online emotion wheel based on Plutchik\'s theory. Identify and express emotions with 24 emotions across 8 basic types and 3 intensity levels. Perfect for therapy, journaling, and self-awareness."'),
        (r'<meta name="keywords" content="[^"]*"', '<meta name="keywords" content="emotion wheel, emotion chart, feelings wheel, plutchik, emotion recognition, emotional intelligence, therapy tool"'),
        (r'<meta property="og:title" content="[^"]*"', '<meta property="og:title" content="Emotion Wheel - Online Emotion Recognition Tool | Free ToolBase"'),
        (r'<meta property="og:description" content="[^"]*"', '<meta property="og:description" content="Free online emotion wheel based on Plutchik\'s theory. Identify and express emotions with 24 emotions across 8 basic types and 3 intensity levels."'),
        (r'content="https://free-toolbase.com/emotion-wheel/"', 'content="https://free-toolbase.com/en/emotion-wheel/"'),
        (r'href="\.\./en/emotion-wheel/"', 'href="../../emotion-wheel/"'),
        (r'hreflang="zh".*?/>', 'hreflang="en" href="https://free-toolbase.com/en/emotion-wheel/">'),
        (r'hreflang="en".*?/>', 'hreflang="zh" href="https://free-toolbase.com/emotion-wheel/">'),
        (r'hreflang="x-default".*?/>', 'hreflang="x-default" href="https://free-toolbase.com/en/emotion-wheel/">'),
        (r'"name":"情绪轮盘"', '"name":"Emotion Wheel"'),
        (r'"免费在线情绪轮盘工具[^"]*"', '"Free online emotion wheel based on Plutchik\'s theory. Identify and express emotions."'),
        (r'<h1>[^<]*</h1>', '<h1>🎭 Emotion Wheel</h1>'),
        (r'<p class="nav-back">.*?</p>', '<p class="nav-back"><a href="../../index.html">Home</a> &rsaquo; <a href="../../index.html#tools">Tools</a> &rsaquo; Emotion Wheel</p>'),
        (r'<a href="index.html" class="active">[^<]*</a>', '<a href="../../emotion-wheel/">中文</a>'),
        (r'<a href="\.\./en/emotion-wheel/">[^<]*</a>', '<a href="index.html" class="active">EN</a>'),
        (r'<p>免费在线情绪轮盘工具[^<]*</p>', '<p>Free online emotion wheel based on Plutchik\'s theory. Helps identify and express inner feelings with 8 basic emotions across 3 intensity levels. Ideal for therapy, journaling, and self-awareness.</p>'),
        ('零依赖·可离线使用', 'Zero Dependencies · Works Offline'),
        ('📋 复制情绪描述', '📋 Copy Description'),
        ('高强度', 'High Intensity'),
        ('中等强度', 'Medium Intensity'),
        ('低强度', 'Low Intensity'),
        ('普拉奇克情绪轮盘理论', "Plutchik's Emotion Wheel Theory"),
        (r'<p><strong>8种基本情绪：</strong>[^<]*</p>', '<p><strong>8 Basic Emotions:</strong> Joy, Trust, Fear, Surprise, Sadness, Disgust, Anger, Anticipation. These combine like primary colors to form complex feelings.</p>'),
        (r'<p><strong>三个强度层级：</strong>[^<]*</p>', '<p><strong>3 Intensity Levels:</strong> Each basic emotion has three intensities — strong (center), medium (middle), weak (outer). Example: Ecstasy → Joy → Serenity.</p>'),
        (r'<p><strong>组合情绪：</strong>[^<]*</p>', '<p><strong>Combined Emotions:</strong> Adjacent emotions mix to create complex feelings, e.g., Joy + Trust = Love, Fear + Surprise = Awe.</p>'),
        (r'<p>点击轮盘上的情绪或下方标签查看详细信息。</p>', '<p>Click on the wheel or emotion chips below to view details.</p>'),
        ('应用场景', 'Use Cases'),
        (r'<p><strong>情绪日记：</strong>[^<]*</p>', '<p><strong>Emotion Journal:</strong> Select an emotion daily, record triggers and coping strategies.</p>'),
        (r'<p><strong>心理咨询：</strong>[^<]*</p>', '<p><strong>Therapy:</strong> Help clients describe feelings with precise vocabulary for better communication.</p>'),
        (r'<p><strong>教育场景：</strong>[^<]*</p>', '<p><strong>Education:</strong> Teach children to recognize emotions and develop emotional intelligence (EQ).</p>'),
        (r'<p><strong>职场沟通：</strong>[^<]*</p>', '<p><strong>Workplace:</strong> Identify team emotional states to improve work atmosphere.</p>'),
        ('情绪轮盘 | 无需注册 · 数据绝不上传服务器', 'Emotion Wheel | No Registration · Data Never Uploads'),
        ('已复制', 'Copied'),
        ('相关情绪：', 'Related emotions: '),
        (r'href="\.\./privacy/"', 'href="../../privacy/"'),
        (r'href="\.\./terms/"', 'href="../../terms/"'),
        (r'href="\.\./about/"', 'href="../../about/"'),
        (r'href="\.\./index.html"', 'href="../../index.html"'),
        ('首页', 'Home'),
        ('全部工具', 'All Tools'),
        ('联系我们', 'Contact'),
        ('隐私政策', 'Privacy'),
        ('服务条款', 'Terms'),
        ('关于我们', 'About'),
        (r'<a href="\.\./en/emotion-wheel/">EN</a>', '<a href="../../emotion-wheel/">中文</a>'),
        ('问题反馈', 'Feedback'),
    ],
    "qr-scanner": [
        (r'lang="zh-CN"', 'lang="en"'),
        (r'<title>.*?</title>', '<title>QR Code Scanner - Online Barcode Scanner Tool | Free ToolBase</title>'),
        (r'<meta name="description" content="[^"]*"', '<meta name="description" content="Free online QR code and barcode scanner. Use your camera to scan QR codes in real-time or upload images for recognition. Supports URL, text, WiFi and more. All browser-based, no data upload."'),
        (r'<meta name="keywords" content="[^"]*"', '<meta name="keywords" content="QR scanner, QR code scanner, online barcode scanner, scan QR, QR reader, barcode reader"'),
        (r'<meta property="og:title" content="[^"]*"', '<meta property="og:title" content="QR Code Scanner - Online Barcode Scanner Tool | Free ToolBase"'),
        (r'<meta property="og:description" content="[^"]*"', '<meta property="og:description" content="Free online QR code and barcode scanner. Use your camera to scan QR codes in real-time or upload images for recognition."'),
        (r'content="https://free-toolbase.com/qr-scanner/"', 'content="https://free-toolbase.com/en/qr-scanner/"'),
        (r'href="\.\./en/qr-scanner/"', 'href="../../qr-scanner/"'),
        (r'hreflang="zh".*?/>', 'hreflang="en" href="https://free-toolbase.com/en/qr-scanner/">'),
        (r'hreflang="en".*?/>', 'hreflang="zh" href="https://free-toolbase.com/qr-scanner/">'),
        (r'hreflang="x-default".*?/>', 'hreflang="x-default" href="https://free-toolbase.com/en/qr-scanner/">'),
        (r'"name":"QR二维码扫描器"', '"name":"QR Code Scanner"'),
        (r'"免费在线QR码/二维码扫描器[^"]*"', '"Free online QR code scanner. Scan with camera or upload images. All browser-based."'),
        (r'<h1>[^<]*</h1>', '<h1>📷 QR Code Scanner</h1>'),
        (r'<p class="nav-back">.*?</p>', '<p class="nav-back"><a href="../../index.html">Home</a> &rsaquo; <a href="../../index.html#tools">Tools</a> &rsaquo; QR Code Scanner</p>'),
        (r'<a href="index.html" class="active">[^<]*</a>', '<a href="../../qr-scanner/">中文</a>'),
        (r'<a href="\.\./en/qr-scanner/">[^<]*</a>', '<a href="index.html" class="active">EN</a>'),
        (r'<p>免费在线QR码/二维码扫描器[^<]*</p>', '<p>Free online QR code / barcode scanner. Scan QR codes in real-time using your camera or upload images for recognition. All processing is local, no data uploaded.</p>'),
        ('零依赖·可离线使用', 'Zero Dependencies · Works Offline'),
        ('📸 开启摄像头扫描', '📸 Start Camera Scan'),
        ('⏹ 停止', '⏹ Stop'),
        ('📁 上传图片扫描', '📁 Upload Image'),
        ('扫描结果', 'Scan Result'),
        ('📋 复制结果', '📋 Copy Result'),
        ('🔗 打开链接', '🔗 Open URL'),
        ('文本', 'Text'),
        ('URL链接', 'URL Link'),
        ('WiFi信息', 'WiFi Info'),
        ('邮箱', 'Email'),
        ('电话', 'Phone'),
        ('使用说明', 'How to Use'),
        ('支持识别类型', 'Supported Types'),
        (r'<p><strong>摄像头扫描：</strong>[^<]*</p>', '<p><strong>Camera Scan:</strong> Click "Start Camera Scan", allow camera access. Point QR code at the viewfinder for automatic detection.</p>'),
        (r'<p><strong>上传图片：</strong>[^<]*</p>', '<p><strong>Upload Image:</strong> Click "Upload Image" and select a QR code image (PNG/JPG supported).</p>'),
        (r'<p><strong>隐私保护：</strong>[^<]*</p>', '<p><strong>Privacy:</strong> All scanning is done locally in your browser. Video and images are never uploaded.</p>'),
        (r'<p><strong>浏览器支持：</strong>[^<]*</p>', '<p><strong>Browser Support:</strong> Chrome/Edge recommended (supports BarcodeDetector API). Firefox/Safari use fallback.</p>'),
        (r'<p><strong>URL链接：</strong>[^<]*</p>', '<p><strong>URL:</strong> Website links, openable with one click.</p>'),
        (r'<p><strong>WiFi信息：</strong>[^<]*</p>', '<p><strong>WiFi:</strong> Network name and password recognition.</p>'),
        (r'<p><strong>文本/数字：</strong>[^<]*</p>', '<p><strong>Text/Numbers:</strong> Plain text, numbers, encoded data.</p>'),
        (r'<p><strong>联系方式：</strong>[^<]*</p>', '<p><strong>Contact:</strong> Email, phone, and vCard information.</p>'),
        ('点击下方按钮开启摄像头', 'Click the button below to start camera'),
        ('QR二维码扫描器 | 无需注册 · 数据绝不上传服务器', 'QR Code Scanner | No Registration · Data Never Uploads'),
        ('摄像头访问失败', 'Camera access failed. Please check permissions'),
        ('扫描成功!', 'Scan successful!'),
        ('未检测到二维码', 'No QR code detected'),
        ('识别出错，请重试', 'Scan error, try again'),
        ('提示: Chrome浏览器扫描效果最佳', 'Tip: Chrome browser works best for scanning'),
        ('已复制', 'Copied'),
        (r'href="\.\./privacy/"', 'href="../../privacy/"'),
        (r'href="\.\./terms/"', 'href="../../terms/"'),
        (r'href="\.\./about/"', 'href="../../about/"'),
        (r'href="\.\./index.html"', 'href="../../index.html"'),
        ('首页', 'Home'),
        ('全部工具', 'All Tools'),
        ('联系我们', 'Contact'),
        ('隐私政策', 'Privacy'),
        ('服务条款', 'Terms'),
        ('关于我们', 'About'),
        (r'<a href="\.\./en/qr-scanner/">EN</a>', '<a href="../../qr-scanner/">中文</a>'),
        ('问题反馈', 'Feedback'),
    ],
}

for name, replacements in tool_configs.items():
    with open(f"{name}/index.html") as f:
        content = f.read()
    for old, new in replacements:
        content = re.sub(old, new, content)
    out_path = f"en/{name}/index.html"
    with open(out_path, "w") as f:
        f.write(content)
    print(f"Generated: {out_path}")

# Verify with node -c
print("\n--- JS Syntax Check ---")
for name in tool_configs:
    path = f"en/{name}/index.html"
    with open(path) as f:
        html = f.read()
    scripts = re.findall(r'<script>(.*?)</script>', html, re.DOTALL)
    for i, s in enumerate(scripts):
        if 'gtag' in s or ('window.addEventListener' in s and 'error' in s):
            continue
        import subprocess
        r = subprocess.run(['node', '-c', '-'], input=s, capture_output=True, text=True)
        if r.returncode != 0:
            print(f"FAIL: en/{name} script[{i}]: {r.stderr.strip()[:80]}")
        else:
            print(f"OK: en/{name}")
print("\nDone.")
