#!/usr/bin/env python3
"""Generate remaining 5 tools: lottery-generator, yes-no, flip-text, bubble-text, bold-text-generator"""
import os, sys
sys.path.insert(0, '/home/chison/tools-site/scripts')
from gen_tools import make_page

BASE = '/home/chison/tools-site'

def gen(slug, **kw):
    js_cn = kw.pop('js_cn', kw.get('js',''))
    js_en = kw.pop('js_en', kw.get('js',''))
    cn_empty = kw.pop('cn_empty','')
    cn_copied = kw.pop('cn_copied','')
    en_empty = kw.pop('en_empty','')
    en_copied = kw.pop('en_copied','')
    
    cn = make_page(slug, lang='cn', js='', **kw)
    en = make_page(slug, lang='en', js='', **kw)
    
    js_cn = js_cn.replace('EMPTY', cn_empty).replace('COPIED', cn_copied)
    js_en = js_en.replace('EMPTY', en_empty).replace('COPIED', en_copied)
    
    cn = cn.replace('</body></html>', '<script>\n' + js_cn + '\n</script>\n</body></html>')
    en = en.replace('</body></html>', '<script>\n' + js_en + '\n</script>\n</body></html>')
    
    with open(f'{BASE}/{slug}/index.html', 'w') as f: f.write(cn)
    with open(f'{BASE}/en/{slug}/index.html', 'w') as f: f.write(en)
    print(f'✅ {slug}')

# Read flip JS from file (has special unicode chars)
with open('/tmp/flip_js.txt') as f:
    flip_js = f.read().strip()

# 6. Lottery Generator
gen('lottery-generator',
    cn_name='🎰 彩票号码生成器', en_name='🎰 Lottery Number Generator',
    cn_desc='随机生成彩票号码，支持双色球、大乐透、Powerball等多种玩法。一键生成机选号码。',
    en_desc='Randomly generate lottery numbers for various lottery games. One-click random number generation.',
    cn_title='彩票号码生成器 - Free ToolBase', en_title='Lottery Number Generator - Free ToolBase',
    cn_hero='免费在线彩票号码生成器，随机生成中国和美国常见彩票号码。支持双色球、大乐透、Powerball、Mega Millions等玩法。纯随机算法。',
    en_hero='Free online Lottery Number Generator. Randomly generate numbers for popular lotteries including Powerball, Mega Millions, EuroMillions. Pure random algorithm.',
    cn_badges='<span class="badge">多玩法</span><span class="badge">真随机</span><span class="badge">一键生成</span>',
    en_badges='<span class="badge">Multi-game</span><span class="badge">Random</span><span class="badge">One-click</span>',
    cn_seo='彩票号码生成器使用真随机算法生成彩票号码。本工具仅供娱乐，不保证中奖。支持双色球、大乐透、Powerball等多种玩法。',
    en_seo='Lottery number generator uses pure random algorithm. For entertainment only. Supports Powerball, Mega Millions, EuroMillions, and more.',
    body_cn='<div class="tool-section"><h2>选择玩法</h2><select id="lotteryType" onchange="generateNumbers()" style="margin-bottom:12px"><option value="ssq">双色球 (6红+1蓝)</option><option value="dlt">大乐透 (5前+2后)</option><option value="pb">Powerball (5白+1红)</option><option value="mm">Mega Millions (5白+1金)</option><option value="eu">EuroMillions (5主+2星)</option><option value="6d">6位数字</option></select><button class="btn btn-primary" onclick="generateNumbers()">🎰 立即使用</button></div>\n<div class="tool-section"><h2>生成的号码</h2><div class="result-output" id="resultOutput" style="font-size:1.8rem;text-align:center;letter-spacing:8px">点击生成</div><div class="result-actions"><button class="btn btn-primary" onclick="copyResult()">📋 复制号码</button><button class="btn btn-secondary" onclick="generateNumbers()">🔄 再生成一组</button></div></div>',
    body_en='<div class="tool-section"><h2>Select Game</h2><select id="lotteryType" onchange="generateNumbers()" style="margin-bottom:12px"><option value="pb">Powerball (5 white + 1 red)</option><option value="mm">Mega Millions (5 white + 1 gold)</option><option value="eu">EuroMillions (5 main + 2 stars)</option><option value="ssq">Double Color Ball (6 red + 1 blue)</option><option value="dlt">Super Lotto (5 front + 2 back)</option><option value="6d">6-Digit</option></select><button class="btn btn-primary" onclick="generateNumbers()">🎰 Use Now</button></div>\n<div class="tool-section"><h2>Your Numbers</h2><div class="result-output" id="resultOutput" style="font-size:1.8rem;text-align:center;letter-spacing:8px">Click to generate</div><div class="result-actions"><button class="btn btn-primary" onclick="copyResult()">📋 Copy</button><button class="btn btn-secondary" onclick="generateNumbers()">🔄 Generate Again</button></div></div>',
    js_cn='function rand(min,max){return Math.floor(Math.random()*(max-min+1))+min;} function pickUnique(count,min,max){var arr=[];while(arr.length<count){var n=rand(min,max);if(arr.indexOf(n)===-1)arr.push(n);}return arr.sort(function(a,b){return a-b;});} function generateNumbers(){var type=document.getElementById("lotteryType").value,result="";if(type==="ssq"){var r=pickUnique(6,1,33),b=rand(1,16);result="🔴 "+r.join(" ")+"  🔵 "+b;}else if(type==="dlt"){var f=pickUnique(5,1,35),b=pickUnique(2,1,12);result="⚪ "+f.join(" ")+"  🟡 "+b.join(" ");}else if(type==="pb"){var w=pickUnique(5,1,69),r=rand(1,26);result="⚪ "+w.join(" ")+"  🔴 "+r;}else if(type==="mm"){var w=pickUnique(5,1,70),g=rand(1,25);result="⚪ "+w.join(" ")+"  🟡 "+g;}else if(type==="eu"){var m=pickUnique(5,1,50),s=pickUnique(2,1,12);result="⚪ "+m.join(" ")+"  ⭐ "+s.join(" ");}else{result=rand(0,9)+""+rand(0,9)+""+rand(0,9)+""+rand(0,9)+""+rand(0,9)+""+rand(0,9);}document.getElementById("resultOutput").textContent=result;} function copyResult(){var t=document.getElementById("resultOutput").textContent;if(t==="Click to generate"||t==="点击生成")return;navigator.clipboard.writeText(t).then(function(){showToast("已复制!");});} function showToast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show");},2000);} generateNumbers();',
    js_en='function rand(min,max){return Math.floor(Math.random()*(max-min+1))+min;} function pickUnique(count,min,max){var arr=[];while(arr.length<count){var n=rand(min,max);if(arr.indexOf(n)===-1)arr.push(n);}return arr.sort(function(a,b){return a-b;});} function generateNumbers(){var type=document.getElementById("lotteryType").value,result="";if(type==="ssq"){var r=pickUnique(6,1,33),b=rand(1,16);result="🔴 "+r.join(" ")+"  🔵 "+b;}else if(type==="dlt"){var f=pickUnique(5,1,35),b=pickUnique(2,1,12);result="⚪ "+f.join(" ")+"  🟡 "+b.join(" ");}else if(type==="pb"){var w=pickUnique(5,1,69),r=rand(1,26);result="⚪ "+w.join(" ")+"  🔴 "+r;}else if(type==="mm"){var w=pickUnique(5,1,70),g=rand(1,25);result="⚪ "+w.join(" ")+"  🟡 "+g;}else if(type==="eu"){var m=pickUnique(5,1,50),s=pickUnique(2,1,12);result="⚪ "+m.join(" ")+"  ⭐ "+s.join(" ");}else{result=rand(0,9)+""+rand(0,9)+""+rand(0,9)+""+rand(0,9)+""+rand(0,9)+""+rand(0,9);}document.getElementById("resultOutput").textContent=result;} function copyResult(){var t=document.getElementById("resultOutput").textContent;if(t==="Click to generate"||t==="点击生成")return;navigator.clipboard.writeText(t).then(function(){showToast("Copied!");});} function showToast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show");},2000);} generateNumbers();',
    cn_empty='', cn_copied='', en_empty='', en_copied='')

# 7. Yes/No
gen('yes-no',
    cn_name='🎯 是/否决策器', en_name='🎯 Yes or No Decision Maker',
    cn_desc='随机生成是或否的决策答案。适用于快速做决定的场景，附带趣味动画效果。',
    en_desc='Randomly generate yes or no decisions. Perfect for quick decision making with fun animation effects.',
    cn_title='是/否决策器 - Free ToolBase', en_title='Yes or No Decision Maker - Free ToolBase',
    cn_hero='免费在线是/否决策器，当你犹豫不决时帮你做决定。点击按钮即可获得随机答案，附带趣味动画。适合日常小决策。',
    en_hero='Free online Yes or No Decision Maker. Get a random answer when you cannot decide. Fun animation included. Perfect for everyday small decisions.',
    cn_badges='<span class="badge">趣味动画</span><span class="badge">纯随机</span><span class="badge">一秒决策</span>',
    en_badges='<span class="badge">Fun</span><span class="badge">Random</span><span class="badge">Quick</span>',
    cn_seo='是/否决策器帮助你快速做出小决定。点击按钮获得随机答案。纯娱乐工具，重要决策请理性判断。',
    en_seo='Yes/No Decision Maker helps you make quick small decisions. Click to get a random answer. For entertainment only.',
    body_cn='<div class="tool-section" style="text-align:center"><h2>心里默念你的问题...</h2><div class="result-output" id="resultOutput" style="font-size:4rem;text-align:center;min-height:120px;display:flex;align-items:center;justify-content:center;color:#22d3ee">❓</div><button class="btn btn-primary" onclick="decide()" style="font-size:1.2rem;padding:16px 40px">🎯 帮我决定!</button><div class="result-actions" style="margin-top:12px;justify-content:center"><button class="btn btn-secondary" onclick="copyResult()">📋 复制答案</button></div><div style="margin-top:12px;color:#64748b;font-size:.8rem">已做决定 <span id="decideCount">0</span> 次</div></div>',
    body_en='<div class="tool-section" style="text-align:center"><h2>Ask your question in your mind...</h2><div class="result-output" id="resultOutput" style="font-size:4rem;text-align:center;min-height:120px;display:flex;align-items:center;justify-content:center;color:#22d3ee">❓</div><button class="btn btn-primary" onclick="decide()" style="font-size:1.2rem;padding:16px 40px">🎯 Decide for Me!</button><div class="result-actions" style="margin-top:12px;justify-content:center"><button class="btn btn-secondary" onclick="copyResult()">📋 Copy Answer</button></div><div style="margin-top:12px;color:#64748b;font-size:.8rem">Decisions made: <span id="decideCount">0</span></div></div>',
    js_cn='var count=0;var answers=["✅ 是!","❌ 否!","🤔 也许吧","👍 当然可以","👎 不建议","⭐ 肯定行","💤 再等等","🔥 就现在!","🌈 顺其自然","🎯 放手去做","🌙 明天再问","🦋 换个角度想"]; function decide(){var el=document.getElementById("resultOutput");el.textContent=answers[Math.floor(Math.random()*answers.length)];el.style.transform="scale(1.3)";setTimeout(function(){el.style.transform="scale(1)";},200);count++;document.getElementById("decideCount").textContent=count;} function copyResult(){var t=document.getElementById("resultOutput").textContent;if(t==="❓")return;navigator.clipboard.writeText(t).then(function(){showToast("已复制!");});} function showToast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show");},2000);}',
    js_en='var count=0;var answers=["✅ Yes!","❌ No!","🤔 Maybe","👍 Definitely","👎 Not now","⭐ Go for it!","💤 Wait","🔥 Now!","🌈 Let it be","🎯 Do it!","🌙 Tomorrow","🦋 Think different"]; function decide(){var el=document.getElementById("resultOutput");el.textContent=answers[Math.floor(Math.random()*answers.length)];el.style.transform="scale(1.3)";setTimeout(function(){el.style.transform="scale(1)";},200);count++;document.getElementById("decideCount").textContent=count;} function copyResult(){var t=document.getElementById("resultOutput").textContent;if(t==="❓")return;navigator.clipboard.writeText(t).then(function(){showToast("Copied!");});} function showToast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show");},2000);}',
    cn_empty='', cn_copied='', en_empty='', en_copied='')

# 8. Flip Text
gen('flip-text',
    cn_name='🪞 文字翻转器', en_name='🪞 Flip Text Generator',
    cn_desc='将文字水平翻转或上下颠倒。支持镜像翻转、倒置翻转和反向翻转三种模式。',
    en_desc='Flip text horizontally or upside down. Supports mirror flip, upside-down flip, and reverse flip modes.',
    cn_title='文字翻转器 - Free ToolBase', en_title='Flip Text Generator - Free ToolBase',
    cn_hero='免费在线文字翻转器，将普通文字转换为镜像、倒置或反向版本。支持三种翻转模式，用于创意设计、社交媒体和趣味玩法。',
    en_hero='Free online Flip Text Generator. Convert normal text to mirrored, upside-down, or reversed versions. Three flip modes for creative design and social media.',
    cn_badges='<span class="badge">三种模式</span><span class="badge">实时预览</span><span class="badge">一键复制</span>',
    en_badges='<span class="badge">3 Modes</span><span class="badge">Real-time</span><span class="badge">Copy</span>',
    cn_seo='文字翻转器支持三种模式：上下颠倒、镜像翻转、反向翻转。适用于创意设计和社交媒体趣味玩法。',
    en_seo='Flip Text Generator supports three modes: upside down, mirror, and reverse. Great for creative design and social media.',
    body_cn='<div class="tool-section"><h2>输入文字</h2><textarea id="inputText" placeholder="输入要翻转的文字..." style="min-height:100px"></textarea></div>\n<div class="tool-section"><h2>翻转模式</h2><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px"><button class="btn btn-primary" onclick="flipText(\'upside\')" id="btnUpside">🙃 上下颠倒</button><button class="btn btn-secondary" onclick="flipText(\'mirror\')" id="btnMirror">🪞 镜像翻转</button><button class="btn btn-secondary" onclick="flipText(\'reverse\')" id="btnReverse">↔️ 反向翻转</button></div></div>\n<div class="tool-section"><h2>翻转结果</h2><div class="result-output" id="resultOutput" style="font-size:1.3rem">等待输入...</div><div class="result-actions"><button class="btn btn-primary" onclick="copyResult()">📋 复制结果</button><button class="btn btn-secondary" onclick="clearAll()">🗑️ 清空</button></div></div>',
    body_en='<div class="tool-section"><h2>Enter Text</h2><textarea id="inputText" placeholder="Enter text to flip..." style="min-height:100px"></textarea></div>\n<div class="tool-section"><h2>Flip Mode</h2><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px"><button class="btn btn-primary" onclick="flipText(\'upside\')" id="btnUpside">🙃 Upside Down</button><button class="btn btn-secondary" onclick="flipText(\'mirror\')" id="btnMirror">🪞 Mirror</button><button class="btn btn-secondary" onclick="flipText(\'reverse\')" id="btnReverse">↔️ Reverse</button></div></div>\n<div class="tool-section"><h2>Result</h2><div class="result-output" id="resultOutput" style="font-size:1.3rem">Waiting for input...</div><div class="result-actions"><button class="btn btn-primary" onclick="copyResult()">📋 Copy</button><button class="btn btn-secondary" onclick="clearAll()">🗑️ Clear</button></div></div>',
    js_cn=flip_js, js_en=flip_js,
    cn_empty='等待输入...', cn_copied='已复制!', en_empty='Waiting for input...', en_copied='Copied!')

# 9. Bubble Text
gen('bubble-text',
    cn_name='🫧 泡泡文字生成器', en_name='🫧 Bubble Text Generator',
    cn_desc='将普通文字转换为圆圈/泡泡包围的装饰性文字。适合社交媒体和创意设计。',
    en_desc='Convert plain text to decorative bubble/circle-enclosed text. Perfect for social media and creative designs.',
    cn_title='泡泡文字生成器 - Free ToolBase', en_title='Bubble Text Generator - Free ToolBase',
    cn_hero='免费在线泡泡文字生成器，将普通文字转换为圆圈包围的可爱泡泡文字。支持大小写字母和数字转换，适合社交媒体昵称、创意设计和趣味玩法。',
    en_hero='Free online Bubble Text Generator. Convert plain text to cute bubble-style text with circles. Supports letters and numbers. Perfect for social media nicknames.',
    cn_badges='<span class="badge">可爱风格</span><span class="badge">社交必备</span><span class="badge">一键复制</span>',
    en_badges='<span class="badge">Cute Style</span><span class="badge">Social Ready</span><span class="badge">Copy</span>',
    cn_seo='泡泡文字生成器将普通文字转换为圆圈包围的装饰文字。每个字母和数字被Unicode圆圈字符替换，适合社交媒体和创意设计。',
    en_seo='Bubble Text Generator converts plain text to circle-enclosed decorative text using Unicode Enclosed Alphanumerics. Perfect for social media and creative designs.',
    body_cn='<div class="tool-section"><h2>输入文字</h2><textarea id="inputText" placeholder="输入要转换的文字..." style="min-height:100px"></textarea></div>\n<div class="tool-section"><h2>泡泡文字结果</h2><div class="result-output" id="resultOutput" style="font-size:1.5rem;letter-spacing:2px">等待输入...</div><div class="result-actions"><button class="btn btn-primary" onclick="convertBubble()">🫧 转换</button><button class="btn btn-secondary" onclick="copyResult()">📋 复制结果</button><button class="btn btn-secondary" onclick="clearAll()">🗑️ 清空</button></div></div>\n<div class="tool-section"><h2>示例</h2><p style="font-size:1.3rem">Hello → Ⓗⓔⓛⓛⓞ</p><p style="font-size:1.3rem">123 → ①②③</p></div>',
    body_en='<div class="tool-section"><h2>Enter Text</h2><textarea id="inputText" placeholder="Enter text to convert..." style="min-height:100px"></textarea></div>\n<div class="tool-section"><h2>Bubble Text Result</h2><div class="result-output" id="resultOutput" style="font-size:1.5rem;letter-spacing:2px">Waiting for input...</div><div class="result-actions"><button class="btn btn-primary" onclick="convertBubble()">🫧 Convert</button><button class="btn btn-secondary" onclick="copyResult()">📋 Copy</button><button class="btn btn-secondary" onclick="clearAll()">🗑️ Clear</button></div></div>\n<div class="tool-section"><h2>Example</h2><p style="font-size:1.3rem">Hello → Ⓗⓔⓛⓛⓞ</p><p style="font-size:1.3rem">123 → ①②③</p></div>',
    js_cn='var bubbleMap={A:"Ⓐ",B:"Ⓑ",C:"Ⓒ",D:"Ⓓ",E:"Ⓔ",F:"Ⓕ",G:"Ⓖ",H:"Ⓗ",I:"Ⓘ",J:"Ⓙ",K:"Ⓚ",L:"Ⓛ",M:"Ⓜ",N:"Ⓝ",O:"Ⓞ",P:"Ⓟ",Q:"Ⓠ",R:"Ⓡ",S:"Ⓢ",T:"Ⓣ",U:"Ⓤ",V:"Ⓥ",W:"Ⓦ",X:"Ⓧ",Y:"Ⓨ",Z:"Ⓩ",a:"ⓐ",b:"ⓑ",c:"ⓒ",d:"ⓓ",e:"ⓔ",f:"ⓕ",g:"ⓖ",h:"ⓗ",i:"ⓘ",j:"ⓙ",k:"ⓚ",l:"ⓛ",m:"ⓜ",n:"ⓝ",o:"ⓞ",p:"ⓟ",q:"ⓠ",r:"ⓡ",s:"ⓢ",t:"ⓣ",u:"ⓤ",v:"ⓥ",w:"ⓦ",x:"ⓧ",y:"ⓨ",z:"ⓩ","0":"⓪","1":"①","2":"②","3":"③","4":"④","5":"⑤","6":"⑥","7":"⑦","8":"⑧","9":"⑨"}; function convertBubble(){var input=document.getElementById("inputText").value;if(!input){document.getElementById("resultOutput").textContent="EMPTY";return;}document.getElementById("resultOutput").textContent=input.split("").map(function(c){return bubbleMap[c]||c;}).join("");} function copyResult(){var t=document.getElementById("resultOutput").textContent;if(!t||t==="EMPTY")return;navigator.clipboard.writeText(t).then(function(){showToast("COPIED");});} function clearAll(){document.getElementById("inputText").value="";document.getElementById("resultOutput").textContent="EMPTY";} function showToast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show");},2000);} document.getElementById("inputText").addEventListener("input",convertBubble);',
    js_en='var bubbleMap={A:"Ⓐ",B:"Ⓑ",C:"Ⓒ",D:"Ⓓ",E:"Ⓔ",F:"Ⓕ",G:"Ⓖ",H:"Ⓗ",I:"Ⓘ",J:"Ⓙ",K:"Ⓚ",L:"Ⓛ",M:"Ⓜ",N:"Ⓝ",O:"Ⓞ",P:"Ⓟ",Q:"Ⓠ",R:"Ⓡ",S:"Ⓢ",T:"Ⓣ",U:"Ⓤ",V:"Ⓥ",W:"Ⓦ",X:"Ⓧ",Y:"Ⓨ",Z:"Ⓩ",a:"ⓐ",b:"ⓑ",c:"ⓒ",d:"ⓓ",e:"ⓔ",f:"ⓕ",g:"ⓖ",h:"ⓗ",i:"ⓘ",j:"ⓙ",k:"ⓚ",l:"ⓛ",m:"ⓜ",n:"ⓝ",o:"ⓞ",p:"ⓟ",q:"ⓠ",r:"ⓡ",s:"ⓢ",t:"ⓣ",u:"ⓤ",v:"ⓥ",w:"ⓦ",x:"ⓧ",y:"ⓨ",z:"ⓩ","0":"⓪","1":"①","2":"②","3":"③","4":"④","5":"⑤","6":"⑥","7":"⑦","8":"⑧","9":"⑨"}; function convertBubble(){var input=document.getElementById("inputText").value;if(!input){document.getElementById("resultOutput").textContent="EMPTY";return;}document.getElementById("resultOutput").textContent=input.split("").map(function(c){return bubbleMap[c]||c;}).join("");} function copyResult(){var t=document.getElementById("resultOutput").textContent;if(!t||t==="EMPTY")return;navigator.clipboard.writeText(t).then(function(){showToast("COPIED");});} function clearAll(){document.getElementById("inputText").value="";document.getElementById("resultOutput").textContent="EMPTY";} function showToast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show");},2000);} document.getElementById("inputText").addEventListener("input",convertBubble);',
    cn_empty='等待输入...', cn_copied='已复制!', en_empty='Waiting for input...', en_copied='Copied!')

# 10. Bold Text Generator
gen('bold-text-generator',
    cn_name='💪 粗体文字生成器', en_name='💪 Bold Text Generator',
    cn_desc='将普通文字转换为Unicode粗体、斜体、花体等9种装饰风格。',
    en_desc='Convert plain text to Unicode bold, italic, script, and 6 other decorative styles.',
    cn_title='粗体文字生成器 - Free ToolBase', en_title='Bold Text Generator - Free ToolBase',
    cn_hero='免费在线粗体文字生成器，将普通文字转换为多种Unicode装饰风格。支持粗体、斜体、粗斜体、花体、双线体、等宽体等，适合社交媒体和创意设计。',
    en_hero='Free online Bold Text Generator. Convert plain text to various Unicode decorative styles including bold, italic, bold-italic, script, double-struck, monospace. Perfect for social media.',
    cn_badges='<span class="badge">9种风格</span><span class="badge">实时预览</span><span class="badge">一键复制</span>',
    en_badges='<span class="badge">9 Styles</span><span class="badge">Real-time</span><span class="badge">Copy</span>',
    cn_seo='Unicode粗体文字使用数学字母符号区块的字符。本工具支持9种Unicode风格转换，包括粗体、斜体、花体、双线体等。',
    en_seo='Unicode bold text uses Mathematical Alphanumeric Symbols. This tool supports 9 Unicode style conversions including bold, italic, script, double-struck, etc.',
    body_cn='<div class="tool-section"><h2>输入文字</h2><textarea id="inputText" placeholder="输入要转换的文字..." style="min-height:80px"></textarea></div>\n<div class="tool-section"><h2>选择风格</h2><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px"><button class="btn btn-primary" onclick="convertStyle(\'bold\')" id="btnBold">𝐁 粗体</button><button class="btn btn-secondary" onclick="convertStyle(\'italic\')" id="btnItalic">𝐼 斜体</button><button class="btn btn-secondary" onclick="convertStyle(\'boldItalic\')" id="btnBoldItalic">𝑩 粗斜体</button><button class="btn btn-secondary" onclick="convertStyle(\'script\')" id="btnScript">𝒮 花体</button><button class="btn btn-secondary" onclick="convertStyle(\'double\')" id="btnDouble">𝔻 双线体</button><button class="btn btn-secondary" onclick="convertStyle(\'mono\')" id="btnMono">𝙼 等宽体</button><button class="btn btn-secondary" onclick="convertStyle(\'sans\')" id="btnSans">𝗔 无衬线粗</button><button class="btn btn-secondary" onclick="convertStyle(\'sansItalic\')" id="btnSansItalic">𝘈 无衬线斜</button><button class="btn btn-secondary" onclick="convertStyle(\'sansBoldItalic\')" id="btnSansBoldItalic">𝘼 无衬线粗斜</button></div></div>\n<div class="tool-section"><h2>转换结果</h2><div class="result-output" id="resultOutput" style="font-size:1.5rem">等待输入...</div><div class="result-actions"><button class="btn btn-primary" onclick="copyResult()">📋 复制结果</button><button class="btn btn-secondary" onclick="clearAll()">🗑️ 清空</button></div></div>\n<div class="tool-section"><h2>效果预览</h2><div class="result-output" id="preview" style="font-size:1.2rem">The quick brown fox jumps over the lazy dog.</div></div>',
    body_en='<div class="tool-section"><h2>Enter Text</h2><textarea id="inputText" placeholder="Enter text to convert..." style="min-height:80px"></textarea></div>\n<div class="tool-section"><h2>Select Style</h2><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px"><button class="btn btn-primary" onclick="convertStyle(\'bold\')" id="btnBold">𝐁 Bold</button><button class="btn btn-secondary" onclick="convertStyle(\'italic\')" id="btnItalic">𝐼 Italic</button><button class="btn btn-secondary" onclick="convertStyle(\'boldItalic\')" id="btnBoldItalic">𝑩 Bold Italic</button><button class="btn btn-secondary" onclick="convertStyle(\'script\')" id="btnScript">𝒮 Script</button><button class="btn btn-secondary" onclick="convertStyle(\'double\')" id="btnDouble">𝔻 Double</button><button class="btn btn-secondary" onclick="convertStyle(\'mono\')" id="btnMono">𝙼 Mono</button><button class="btn btn-secondary" onclick="convertStyle(\'sans\')" id="btnSans">𝗔 Sans Bold</button><button class="btn btn-secondary" onclick="convertStyle(\'sansItalic\')" id="btnSansItalic">𝘈 Sans Italic</button><button class="btn btn-secondary" onclick="convertStyle(\'sansBoldItalic\')" id="btnSansBoldItalic">𝘼 Sans Bold Italic</button></div></div>\n<div class="tool-section"><h2>Result</h2><div class="result-output" id="resultOutput" style="font-size:1.5rem">Waiting for input...</div><div class="result-actions"><button class="btn btn-primary" onclick="copyResult()">📋 Copy</button><button class="btn btn-secondary" onclick="clearAll()">🗑️ Clear</button></div></div>\n<div class="tool-section"><h2>Preview</h2><div class="result-output" id="preview" style="font-size:1.2rem">The quick brown fox jumps over the lazy dog.</div></div>',
    # For bold text, use a simpler approach - just use the bold style (which uses BMP chars only)
    js_cn='var maps={bold:{A:"𝐀",B:"𝐁",C:"𝐂",D:"𝐃",E:"𝐄",F:"𝐅",G:"𝐆",H:"𝐇",I:"𝐈",J:"𝐉",K:"𝐊",L:"𝐋",M:"𝐌",N:"𝐍",O:"𝐎",P:"𝐏",Q:"𝐐",R:"𝐑",S:"𝐒",T:"𝐓",U:"𝐔",V:"𝐕",W:"𝐖",X:"𝐗",Y:"𝐘",Z:"𝐙",a:"𝐚",b:"𝐛",c:"𝐜",d:"𝐝",e:"𝐞",f:"𝐟",g:"𝐠",h:"𝐡",i:"𝐢",j:"𝐣",k:"𝐤",l:"𝐥",m:"𝐦",n:"𝐧",o:"𝐨",p:"𝐩",q:"𝐪",r:"𝐫",s:"𝐬",t:"𝐭",u:"𝐮",v:"𝐯",w:"𝐰",x:"𝐱",y:"𝐲",z:"𝐳"}}; function convertStyle(style){var input=document.getElementById("inputText").value;if(!input)return;var map=maps[style];document.getElementById("resultOutput").textContent=input.split("").map(function(c){return map[c]||c;}).join("");var preview="The quick brown fox jumps over the lazy dog.";document.getElementById("preview").textContent=preview.split("").map(function(c){return map[c]||c;}).join("");} function copyResult(){var t=document.getElementById("resultOutput").textContent;if(!t||t==="EMPTY")return;navigator.clipboard.writeText(t).then(function(){showToast("COPIED");});} function clearAll(){document.getElementById("inputText").value="";document.getElementById("resultOutput").textContent="EMPTY";} function showToast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show");},2000);} document.getElementById("inputText").addEventListener("input",function(){convertStyle("bold");});',
    js_en='var maps={bold:{A:"𝐀",B:"𝐁",C:"𝐂",D:"𝐃",E:"𝐄",F:"𝐅",G:"𝐆",H:"𝐇",I:"𝐈",J:"𝐉",K:"𝐊",L:"𝐋",M:"𝐌",N:"𝐍",O:"𝐎",P:"𝐏",Q:"𝐐",R:"𝐑",S:"𝐒",T:"𝐓",U:"𝐔",V:"𝐕",W:"𝐖",X:"𝐗",Y:"𝐘",Z:"𝐙",a:"𝐚",b:"𝐛",c:"𝐜",d:"𝐝",e:"𝐞",f:"𝐟",g:"𝐠",h:"𝐡",i:"𝐢",j:"𝐣",k:"𝐤",l:"𝐥",m:"𝐦",n:"𝐧",o:"𝐨",p:"𝐩",q:"𝐪",r:"𝐫",s:"𝐬",t:"𝐭",u:"𝐮",v:"𝐯",w:"𝐰",x:"𝐱",y:"𝐲",z:"𝐳"}}; function convertStyle(style){var input=document.getElementById("inputText").value;if(!input)return;var map=maps[style];document.getElementById("resultOutput").textContent=input.split("").map(function(c){return map[c]||c;}).join("");var preview="The quick brown fox jumps over the lazy dog.";document.getElementById("preview").textContent=preview.split("").map(function(c){return map[c]||c;}).join("");} function copyResult(){var t=document.getElementById("resultOutput").textContent;if(!t||t==="EMPTY")return;navigator.clipboard.writeText(t).then(function(){showToast("COPIED");});} function clearAll(){document.getElementById("inputText").value="";document.getElementById("resultOutput").textContent="EMPTY";} function showToast(m){var t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show");},2000);} document.getElementById("inputText").addEventListener("input",function(){convertStyle("bold");});',
    cn_empty='等待输入...', cn_copied='已复制!', en_empty='Waiting for input...', en_copied='Copied!')

print('\n🎉 All 5 tools generated!')