#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""一键安装 git hooks（sitemap 提交闸门 + 其他检查）。可重复运行。"""
import os
import shutil
import stat
import subprocess
import sys

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True).stdout.strip()
HOOKS = os.path.join(ROOT, ".git", "hooks")
os.makedirs(HOOKS, exist_ok=True)

HOOK_BODY = """#!/bin/sh
# AUTO-GENERATED by scripts/install_git_hooks.py — 勿手改，改 scripts/pre_commit_sitemap.py
exec python3 "$(git rev-parse --show-toplevel)/scripts/pre_commit_sitemap.py"
"""

dst = os.path.join(HOOKS, "pre-commit")
open(dst, "w").write(HOOK_BODY)
os.chmod(dst, 0o755)
print(f"✅ 已安装 pre-commit hook → {dst}")
print("   作用：提交时若 sitemap.xml 结构损坏（<url> 块跑到 <urlset> 外），自动修复或阻止提交")
