#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""一键安装 git hooks（sitemap 提交闸门 + 其他检查）。可重复运行。"""
import os
import shutil
import stat
import subprocess
import sys

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True).stdout.strip()
HOOKS = os.path.join(ROOT, ".git", "hooks")
os.makedirs(HOOKS, exist_ok=True)

HOOK_BODY = """#!/bin/sh
# AUTO-GENERATED by scripts/install_git_hooks.py — 勿手改，改 scripts/pre_commit_*.py
ROOT="$(git rev-parse --show-toplevel)"
# 0) 🔴🔴 ID 铁律闸门（最高优先级）—— GA G-QVBQNJ3L5E / Adsterra pl31040516 / Bing msvalidate.01 / Google 验证文件
#    新增页面缺 ID、带废弃 ID（G-9W1157EBQV、ca-pub-*）一律拦下，不许提交
python3 "$ROOT/scripts/validate_ids.py" || exit 1
# 1) 本次改动页面的 sitemap <lastmod> 同步为今天（并 git add）
python3 "$ROOT/scripts/pre_commit_lastmod.py" || exit 1
# 2) sitemap 结构闸门
python3 "$ROOT/scripts/pre_commit_sitemap.py" || exit 1
# 3) 模板伪内容闸门（Meta description / 正文）
python3 "$ROOT/scripts/pre_commit_template_junk.py" || exit 1
# 4) lastmod 一致性闸门（最后一道）
python3 "$ROOT/scripts/validate_lastmod.py" || exit 1
exit 0
"""

POST_HOOK_BODY = """#!/bin/sh
# AUTO-GENERATED by scripts/install_git_hooks.py — 勿手改
ROOT="$(git rev-parse --show-toplevel)"
# IndexNow 后台提交本次改动页面，绝不阻塞 git，失败只记日志
nohup python3 "$ROOT/scripts/post_commit_indexnow.py" >> /tmp/indexnow_submit.log 2>&1 &
exit 0
"""

for name, body in (("pre-commit", HOOK_BODY), ("post-commit", POST_HOOK_BODY)):
    dst = os.path.join(HOOKS, name)
    open(dst, "w").write(body)
    os.chmod(dst, 0o755)
    print(f"✅ 已安装 {name} hook → {dst}")
print("   作用：pre-commit⓪ 🔴ID 铁律闸门（GA/Adsterra/Bing/Google验证）；① 同步 lastmod；② 校 sitemap 结构；③ 挡模板伪内容；④ lastmod 一致性")
print("         post-commit：后台 IndexNow 推送本次改动页面（不阻塞提交）")
