#!/usr/bin/env python3
"""Post-process EN pages: replace remaining Chinese text with English."""
import os

EN_DIR = '/home/chison/tools-site/en'

# Per-tool full Chinese-to-English text replacements
PATCHES = {
    'option-price-calculator': [
        ('<h1>📈 期权定价计算器</h1>', '<h1>📈 Option Price Calculator</h1>'),
        ('lang-switch"><a href="index.html" class="active">中文</a><a href="../en/', 'lang-switch"><a href="../../option-price-calculator/">中文</a><a href="index.html" class="active">EN</a>'),
        ('<a href="../index.html">首页</a> › <a href="../index.html#tools">工具</a> › 期权定价计算器</p>',
         '<a href="../../index.html">Home</a> › <a href="../../index.html#tools">Tools</a> › Option Price Calculator</p>'),
        ('基于Black-Scholes模型计算欧式看涨/看跌期权理论价格。输入标的资产价格、行权价、到期时间等参数，即可获取期权公允价值及希腊字母。',
         'Calculate European call/put option theoretical prices using the Black-Scholes model. Enter spot price, strike, time to expiry and other parameters to get fair value and Greeks.'),
        ('金融分析 · 投资参考', 'Financial Analysis · Investment Reference'),
        ('📊 输入参数', '📊 Input Parameters'),
        ('标的资产现价 ($)', 'Spot Price ($)'),
        ('当前股票/资产的市场价格', 'Current market price of the underlying asset'),
        ('行权价 ($)', 'Strike Price ($)'),
        ('期权合约约定的行权价格', 'The strike price specified in the option contract'),
        ('距到期天数', 'Days to Expiry'),
        ('期权合约剩余有效天数', 'Remaining days until option expiration'),
        ('无风险利率 (%)', 'Risk-Free Rate (%)'),
        ('通常参考国债收益率，如3.5%', 'Typically the treasury yield, e.g. 3.5%'),
        ('波动率 (%)', 'Volatility (%)'),
        ('年化波动率，个股通常20-60%', 'Annualized volatility, typically 20-60% for stocks'),
        ('股息率 (%)', 'Dividend Yield (%)'),
        ('标的资产的年化股息率（可选）', 'Annualized dividend yield of the underlying (optional)'),
        ('🔍 计算期权价格', '🔍 Calculate Option Price'),
        ('🔄 清除', '🔄 Clear'),
        ('📋 复制结果', '📋 Copy Results'),
        ('💰 期权价格', '💰 Option Prices'),
        ('📈 看涨期权 (Call)', '📈 Call Option'),
        ('📉 看跌期权 (Put)', '📉 Put Option'),
        ('🔢 希腊字母', '🔢 Greeks'),
        ('📖 关于Black-Scholes模型', '📖 About the Black-Scholes Model'),
        ('Black-Scholes模型是期权定价的经典公式，用于计算欧式期权的理论价格。模型假设标的资产价格服从对数正态分布，市场无摩擦，可连续交易。',
         'The Black-Scholes model is the classic option pricing formula for calculating theoretical prices of European options. It assumes log-normal distribution of the underlying, frictionless markets, and continuous trading.'),
        ('核心公式', 'Core Formula'),
        ('免责声明', 'Disclaimer'),
        ('本计算器仅用于学习参考，不构成投资建议。期权交易风险极高，可能导致本金全部损失。实际市场价格受流动性、供需等多因素影响，与模型理论价可能存在差异。',
         'This calculator is for educational reference only and does not constitute investment advice. Options trading carries extremely high risk and may result in total loss of principal. Actual market prices may differ from model theoretical values due to liquidity, supply/demand and other factors.'),
        ('计算完成', 'Calculation complete'),
        ('已复制到剪贴板', 'Copied to clipboard'),
        ('请输入有效的参数', 'Please enter valid parameters'),
        ('期权定价结果', 'Option Pricing Results'),
        ('看涨期权:', 'Call:'),
        ('看跌期权:', 'Put:'),
    ],
    'symptom-checker': [
        ('<h1>🏥 症状自查工具</h1>', '<h1>🏥 Symptom Checker</h1>'),
        ('lang-switch"><a href="index.html" class="active">中文</a><a href="../en/', 'lang-switch"><a href="../../symptom-checker/">中文</a><a href="index.html" class="active">EN</a>'),
        ('<a href="../index.html">首页</a> › <a href="../index.html#tools">工具</a> › 症状自查工具</p>',
         '<a href="../../index.html">Home</a> › <a href="../../index.html#tools">Tools</a> › Symptom Checker</p>'),
        ('选择身体部位和症状，了解可能的健康信息。本工具仅用于健康知识科普，不能替代专业医疗诊断。',
         'Select body parts and symptoms to learn about possible health conditions. This tool is for health education only and cannot replace professional medical diagnosis.'),
        ('健康科普 · 仅供参考', 'Health Education · Reference Only'),
        ('⚠️ <strong>免责声明：</strong>本工具仅提供健康教育参考，不能替代医生诊断。如症状严重或持续，请立即就医。',
         '⚠️ <strong>Disclaimer:</strong> This tool provides health education reference only and cannot replace medical diagnosis. If symptoms are severe or persistent, seek medical attention immediately.'),
        ('🫁 选择身体部位', '🫁 Select Body Part'),
        ('🤒 选择症状（可多选）', '🤒 Select Symptoms (multi-select)'),
        ('🔍 查看参考信息', '🔍 View Reference Info'),
        ('🔄 重置', '🔄 Reset'),
        ('📋 参考信息', '📋 Reference Information'),
        ('📋 复制结果', '📋 Copy Results'),
        ('📖 使用说明', '📖 Instructions'),
        ('选择您关心的身体部位。', 'Select the body part you are concerned about.'),
        ('勾选您感受到的具体症状。', 'Check the specific symptoms you are experiencing.'),
        ('点击"查看参考信息"获取健康知识科普。', 'Click "View Reference Info" to get health knowledge.'),
        ('所有数据在本地处理，不上传服务器，保护您的隐私。', 'All data is processed locally, not uploaded to any server, protecting your privacy.'),
        ('已显示', 'Displayed '),
        ('条参考信息', ' reference items'),
        ('已重置', 'Reset'),
        ('无内容可复制', 'No content to copy'),
        ('症状自查结果:', 'Symptom Check Results:'),
        ('暂无相关参考信息', 'No relevant reference information found'),
        ('请至少选择一个症状', 'Please select at least one symptom'),
        # Knowledge base
        ('头痛', 'Headache'),
        ('头晕', 'Dizziness'),
        ('胸闷', 'Chest Tightness'),
        ('心悸', 'Palpitations'),
        ('腹痛', 'Abdominal Pain'),
        ('腹胀', 'Bloating'),
        ('关节痛', 'Joint Pain'),
        ('肌肉酸痛', 'Muscle Soreness'),
        ('皮疹', 'Rash'),
        ('咳嗽', 'Cough'),
        ('紧张性头痛', 'Tension Headache'),
        ('最常见头痛类型，感觉像头部被紧箍。可能与压力、疲劳、姿势不良有关。', 'Most common headache type, feels like a tight band around the head. May be related to stress, fatigue, or poor posture.'),
        ('偏头痛', 'Migraine'),
        ('单侧搏动性头痛，可能伴恶心、畏光。持续时间4-72小时。', 'Unilateral throbbing headache, may include nausea and photophobia. Lasts 4-72 hours.'),
        ('丛集性头痛', 'Cluster Headache'),
        ('单侧剧烈疼痛，集中在眼周，发作时间短但频率高。', 'Severe unilateral pain focused around the eye, short duration but high frequency.'),
        ('良性位置性眩晕', 'Benign Positional Vertigo'),
        ('头部位置改变时出现短暂眩晕，内耳耳石脱落导致。', 'Brief vertigo with head position changes, caused by inner ear otolith displacement.'),
        ('低血压/贫血', 'Low Blood Pressure / Anemia'),
        ('从坐位站起时头晕，可能伴有眼花、乏力。', 'Dizziness when standing from sitting, may include lightheadedness and fatigue.'),
        ('焦虑/压力', 'Anxiety / Stress'),
        ('心理因素导致胸部紧绷感，深呼吸可缓解。', 'Psychological factor causing chest tightness, relieved by deep breathing.'),
        ('心绞痛', 'Angina'),
        ('胸骨后压迫感，活动时加重，休息缓解。需及时就医。', 'Substernal pressure, worsens with activity, relieved by rest. Seek medical attention.'),
        ('心律不齐', 'Arrhythmia'),
        ('感觉心跳过快、过慢或不规则搏动。咖啡因、压力可诱发。', 'Sensation of fast, slow or irregular heartbeat. Caffeine and stress can trigger.'),
        ('焦虑发作', 'Anxiety Attack'),
        ('伴随心慌、出汗、呼吸急促。心理因素引发。', 'Accompanied by palpitations, sweating, rapid breathing. Triggered by psychological factors.'),
        ('消化不良', 'Indigestion'),
        ('上腹部不适、胀气，与饮食有关。', 'Upper abdominal discomfort, bloating, related to diet.'),
        ('胃肠炎', 'Gastroenteritis'),
        ('腹痛伴腹泻、恶心、呕吐，多为病毒或细菌感染。', 'Abdominal pain with diarrhea, nausea, vomiting. Usually viral or bacterial infection.'),
        ('阑尾炎', 'Appendicitis'),
        ('右下腹持续性疼痛，按压痛明显，常伴发热。需急诊。', 'Persistent right lower abdominal pain with tenderness, often with fever. Requires emergency care.'),
        ('功能性腹胀', 'Functional Bloating'),
        ('肠道气体过多，与饮食、肠道菌群相关。', 'Excess intestinal gas, related to diet and gut flora.'),
        ('肠易激综合征', 'Irritable Bowel Syndrome'),
        ('反复腹胀、腹痛伴排便习惯改变。', 'Recurrent bloating and abdominal pain with changes in bowel habits.'),
        ('骨关节炎', 'Osteoarthritis'),
        ('关节退行性变，晨僵<30分钟，活动后改善。', 'Degenerative joint changes, morning stiffness <30 min, improves with activity.'),
        ('类风湿关节炎', 'Rheumatoid Arthritis'),
        ('对称性多关节肿痛，晨僵>1小时。自身免疫疾病。', 'Symmetrical polyarthritis with swelling, morning stiffness >1 hour. Autoimmune disease.'),
        ('痛风', 'Gout'),
        ('大脚趾等关节突发剧痛、红肿热痛，与高尿酸相关。', 'Sudden severe pain, redness, swelling in joints like the big toe, related to high uric acid.'),
        ('运动后延迟性酸痛', 'Delayed Onset Muscle Soreness'),
        ('运动后24-72小时肌肉酸痛，正常生理反应。', 'Muscle soreness 24-72 hours after exercise, normal physiological response.'),
        ('纤维肌痛', 'Fibromyalgia'),
        ('全身广泛疼痛、疲劳、睡眠障碍。', 'Widespread pain, fatigue, and sleep disturbance.'),
        ('湿疹', 'Eczema'),
        ('皮肤干燥、红斑、瘙痒，常有渗出。', 'Dry skin, erythema, itching, often with exudation.'),
        ('荨麻疹', 'Urticaria'),
        ('红色风团，瘙痒，大小不等，可自行消退再复发。', 'Red wheals, itching, variable size, can resolve and recur spontaneously.'),
        ('药疹', 'Drug Eruption'),
        ('用药后出现皮疹，需停药就医。', 'Rash after medication use, requires discontinuation and medical attention.'),
        ('上呼吸道感染', 'Upper Respiratory Infection'),
        ('感冒引起的咳嗽，通常伴流涕、咽痛，1-2周自愈。', 'Cough from common cold, usually with runny nose and sore throat, self-resolves in 1-2 weeks.'),
        ('过敏性咳嗽', 'Allergic Cough'),
        ('接触过敏原后干咳，伴打喷嚏、鼻痒。', 'Dry cough after allergen exposure, with sneezing and nasal itching.'),
        ('慢性支气管炎', 'Chronic Bronchitis'),
        ('每年咳嗽>3个月，连续>2年，吸烟是主因。', 'Cough >3 months per year for >2 consecutive years, smoking is the main cause.'),
        ('常见', 'Common'),
        ('较少见', 'Uncommon'),
        ('需就医', 'See Doctor'),
        ('需关注', 'Monitor'),
        ('急诊', 'Emergency'),
        ('正常', 'Normal'),
    ],
    'pill-reminder': [
        ('<h1>💊 服药提醒工具</h1>', '<h1>💊 Pill Reminder</h1>'),
        ('lang-switch"><a href="index.html" class="active">中文</a><a href="../en/', 'lang-switch"><a href="../../pill-reminder/">中文</a><a href="index.html" class="active">EN</a>'),
        ('<a href="../index.html">首页</a> › <a href="../index.html#tools">工具</a> › 服药提醒工具</p>',
         '<a href="../../index.html">Home</a> › <a href="../../index.html#tools">Tools</a> › Pill Reminder</p>'),
        ('添加药品、设置剂量和服药时间，自动生成每日服药时间表。支持桌面通知提醒，数据本地存储保护隐私。',
         'Add medications, set dosage and times, automatically generate a daily medication schedule. Supports desktop notifications with local storage for privacy.'),
        ('本机存储 · 隐私保护', 'Local Storage · Privacy Protected'),
        ('⚠️ <strong>重要提示：</strong>本工具为辅助提醒，不能替代医嘱。请严格遵医嘱服药，如有疑问咨询医生或药师。',
         '⚠️ <strong>Important:</strong> This tool is an aid and cannot replace medical advice. Please follow your doctor\'s prescription. Consult your doctor or pharmacist if in doubt.'),
        ('➕ 添加药品', '➕ Add Medication'),
        ('药品名称', 'Medication Name'),
        ('如：阿莫西林', 'e.g. Amoxicillin'),
        ('每次剂量', 'Dosage'),
        ('如：500mg / 1片', 'e.g. 500mg / 1 tablet'),
        ('⏰ 添加更多时间', '⏰ Add More Times'),
        ('📋 药品列表', '📋 Medication List'),
        ('暂无药品，请在上面添加', 'No medications yet. Add one above.'),
        ('🗑 清空所有药品', '🗑 Clear All Medications'),
        ('🔔 启用桌面提醒', '🔔 Enable Desktop Notifications'),
        ('📅 今日服药时间表', '📅 Today\'s Medication Schedule'),
        ('时间', 'Time'),
        ('药品', 'Medication'),
        ('剂量', 'Dosage'),
        ('状态', 'Status'),
        ('标记完成', 'Mark Done'),
        ('已完成 ✓', 'Done ✓'),
        ('📖 使用说明', '📖 Instructions'),
        ('输入药品名称和每次剂量。', 'Enter medication name and dosage per dose.'),
        ('设置每日服药时间（可添加多个时间点）。', 'Set daily medication times (multiple time points supported).'),
        ('点击添加，药品会自动保存到浏览器本地存储。', 'Click add, medications are auto-saved to browser local storage.'),
        ('如需桌面通知，点击"启用桌面提醒"并授权。', 'For desktop notifications, click "Enable Desktop Notifications" and grant permission.'),
        ('已添加 ', 'Added '),
        ('请输入药品名称', 'Please enter medication name'),
        ('请设置服药时间', 'Please set medication time'),
        ('存储空间不足', 'Storage full'),
        ('已清空', 'Cleared'),
        ('桌面通知已启用', 'Desktop notifications enabled'),
        ('通知权限被拒绝', 'Notification permission denied'),
        ('今日提醒已设置', 'Today\'s reminders set'),
        ('该服用 ', 'Time to take '),
        (' 了！', '!'),
        ('💊 服药提醒', '💊 Pill Reminder'),
        ('确定清空所有药品记录？', 'Clear all medication records?'),
        ('次/日', '/day'),
        ('删除', 'Delete'),
    ],
    'vaccination-schedule': [
        ('<h1>💉 疫苗接种时间表</h1>', '<h1>💉 Vaccination Schedule</h1>'),
        ('lang-switch"><a href="index.html" class="active">中文</a><a href="../en/', 'lang-switch"><a href="../../vaccination-schedule/">中文</a><a href="index.html" class="active">EN</a>'),
        ('<a href="../index.html">首页</a> › <a href="../index.html#tools">工具</a> › 疫苗接种时间表</p>',
         '<a href="../../index.html">Home</a> › <a href="../../index.html#tools">Tools</a> › Vaccination Schedule</p>'),
        ('按年龄段查看推荐疫苗接种计划，支持中国国家免疫规划和美国CDC标准。帮助家长科学安排儿童疫苗接种。',
         'View recommended vaccination schedules by age, supporting China NIP and US CDC standards. Help parents plan children\'s vaccinations scientifically.'),
        ('中/美标准 · 健康科普', 'CN/US Standards · Health Education'),
        ('⚠️ <strong>免责声明：</strong>本工具仅供参考，具体接种方案请遵医嘱和当地疾控中心指导。疫苗信息可能更新，请以官方最新公告为准。',
         '⚠️ <strong>Disclaimer:</strong> This tool is for reference only. Follow your doctor and local CDC guidance for specific vaccination plans. Vaccine information may be updated; refer to the latest official announcements.'),
        ('🔍 查询设置', '🔍 Query Settings'),
        ('参考标准', 'Reference Standard'),
        ('中国国家免疫规划', 'China National Immunization Program'),
        ('美国CDC推荐', 'US CDC Recommended'),
        ('儿童月龄', 'Child Age (months)'),
        ('🔍 查看疫苗计划', '🔍 View Vaccine Schedule'),
        ('📋 显示全部', '📋 Show All'),
        ('📋 复制计划', '📋 Copy Schedule'),
        ('🔔 当前月龄应接种/即将接种', '🔔 Vaccines Due/Upcoming for Current Age'),
        ('📅 完整疫苗时间表', '📅 Complete Vaccination Schedule'),
        ('📖 关于疫苗', '📖 About Vaccines'),
        ('疫苗是预防传染病最有效、最经济的手段。世界卫生组织估计，疫苗每年可防止200-300万人死亡。按时接种疫苗可以保护儿童免受麻疹、脊髓灰质炎、百日咳等严重疾病的威胁。',
         'Vaccines are the most effective and economical way to prevent infectious diseases. The WHO estimates vaccines prevent 2-3 million deaths annually. Timely vaccination protects children from measles, polio, pertussis and other serious diseases.'),
        ('出生时', 'At Birth'),
        ('月龄', 'months'),
        ('岁', 'years'),
        ('当前月龄暂无应接种疫苗，请咨询医生确认。', 'No vaccines due at this age. Please consult your doctor.'),
        ('已筛选月龄:', 'Filtered to age: '),
        ('个月', ' months'),
        ('显示全部疫苗时间表', 'Showing complete vaccine schedule'),
        ('疫苗接种时间表:', 'Vaccination Schedule:'),
        # Vaccine names
        ('乙肝疫苗', 'Hepatitis B Vaccine'),
        ('卡介苗(BCG)', 'BCG Vaccine'),
        ('脊髓灰质炎疫苗(IPV', 'Polio Vaccine (IPV'),
        ('脊髓灰质炎疫苗(OPV', 'Polio Vaccine (OPV'),
        ('百白破疫苗(DTaP', 'DTaP Vaccine'),
        ('百白破疫苗(Tdap', 'Tdap Vaccine'),
        ('麻疹疫苗', 'Measles Vaccine'),
        ('乙脑疫苗', 'Japanese Encephalitis Vaccine'),
        ('A+C群流脑疫苗', 'Meningococcal AC Vaccine'),
        ('白破疫苗(DT)', 'DT Vaccine'),
        ('轮状病毒疫苗(RV)', 'Rotavirus Vaccine'),
        ('百白破+IPV+Hib(DTaP-IPV-Hib)', 'DTaP-IPV-Hib (Pentavalent)'),
        ('肺炎球菌结合疫苗(PCV13', 'Pneumococcal Conjugate Vaccine (PCV13'),
        ('Hib疫苗', 'Hib Vaccine'),
        ('麻腮风疫苗(MMR', 'MMR Vaccine'),
        ('水痘疫苗(VAR', 'Varicella Vaccine'),
        ('HPV疫苗', 'HPV Vaccine'),
        ('脑膜炎球菌疫苗(MCV4)', 'Meningococcal Conjugate Vaccine (MCV4)'),
        ('预防乙型肝炎', 'Prevents hepatitis B'),
        ('预防结核病', 'Prevents tuberculosis'),
        ('预防小儿麻痹症', 'Prevents polio'),
        ('预防百日咳、白喉、破伤风', 'Prevents pertussis, diphtheria, tetanus'),
        ('预防麻疹', 'Prevents measles'),
        ('预防流行性乙型脑炎', 'Prevents Japanese encephalitis'),
        ('预防流行性脑脊髓膜炎', 'Prevents meningococcal meningitis'),
        ('预防白喉、破伤风加强', 'Diphtheria and tetanus booster'),
        ('预防轮状病毒腹泻', 'Prevents rotavirus diarrhea'),
        ('五联疫苗', 'Pentavalent vaccine'),
        ('预防肺炎球菌感染', 'Prevents pneumococcal infection'),
        ('预防b型流感嗜血杆菌', 'Prevents Hib infection'),
        ('预防麻疹、腮腺炎、风疹', 'Prevents measles, mumps, rubella'),
        ('预防水痘', 'Prevents chickenpox'),
        ('预防百日咳、白喉、破伤风加强', 'Tdap booster'),
        ('预防人乳头瘤病毒相关癌症', 'Prevents HPV-related cancers'),
        ('第', 'Dose '),
        ('剂', ''),
        ('加强剂', 'Booster'),
        ('加强', 'Booster'),
    ],
    'grocery-list': [
        ('<h1>🛒 购物清单工具</h1>', '<h1>🛒 Grocery List</h1>'),
        ('lang-switch"><a href="index.html" class="active">中文</a><a href="../en/', 'lang-switch"><a href="../../grocery-list/">中文</a><a href="index.html" class="active">EN</a>'),
        ('<a href="../index.html">首页</a> › <a href="../index.html#tools">工具</a> › 购物清单工具</p>',
         '<a href="../../index.html">Home</a> › <a href="../../index.html#tools">Tools</a> › Grocery List</p>'),
        ('智能分类购物清单，支持蔬菜、水果、肉类等品类管理。数据本地存储，勾选即完成，轻松管理每次购物。',
         'Smart categorized grocery list with categories like vegetables, fruits, meat, etc. Local storage, check-off to complete. Manage every shopping trip easily.'),
        ('本地存储 · 分类管理', 'Local Storage · Categorized'),
        ('➕ 添加购物项', '➕ Add Item'),
        ('物品名称，如：西红柿', 'Item name, e.g. Tomatoes'),
        ('🥬 蔬菜', '🥬 Vegetables'),
        ('🍎 水果', '🍎 Fruits'),
        ('🥩 肉类', '🥩 Meat'),
        ('🐟 海鲜', '🐟 Seafood'),
        ('🥛 乳制品', '🥛 Dairy'),
        ('🥤 饮料', '🥤 Beverages'),
        ('🍪 零食', '🍪 Snacks'),
        ('🧂 调味品', '🧂 Condiments'),
        ('🧹 日用品', '🧹 Household'),
        ('📦 其他', '📦 Other'),
        ('📋 购物清单', '📋 Grocery List'),
        ('总计', 'Total'),
        ('已完成', 'Done'),
        ('待购', 'Pending'),
        ('全部', 'All'),
        ('📝 清单空空如也，添加一些物品吧！', '📝 List is empty. Add some items!'),
        ('✅ 清除已完成', '✅ Clear Done'),
        ('🗑 清空清单', '🗑 Clear All'),
        ('📋 复制清单', '📋 Copy List'),
        ('📖 使用技巧', '📖 Tips'),
        ('输入物品名称和数量，选择分类后点击添加。', 'Enter item name and quantity, select category, then click add.'),
        ('使用分类筛选按钮快速查看某一品类。', 'Use category filter buttons to quickly view a specific category.'),
        ('勾选已购物品，完成后可一键清除已完成项。', 'Check off purchased items. Clear done items with one click.'),
        ('数据自动保存到浏览器，关闭页面不会丢失。', 'Data auto-saves to browser. Won\'t be lost when you close the page.'),
        ('已添加 ', 'Added '),
        ('请输入物品名称', 'Please enter item name'),
        ('存储空间不足', 'Storage full'),
        ('已清除 ', 'Cleared '),
        (' 项已完成', ' done items'),
        ('清单已清空', 'List cleared'),
        ('清单为空', 'List is empty'),
        ('购物清单:', 'Grocery List:'),
        ('该分类暂无物品', 'No items in this category'),
        ('确定清空全部购物清单？', 'Clear entire grocery list?'),
    ],
}

def patch_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    count = 0
    for old, new in replacements:
        if old in content:
            content = content.replace(old, new)
            count += 1

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    return count

for tool, replacements in PATCHES.items():
    filepath = os.path.join(EN_DIR, tool, 'index.html')
    count = patch_file(filepath, replacements)
    print(f'{tool}: {count}/{len(replacements)} replacements applied')