#!/usr/bin/env python3
"""Translate CN tool pages to EN"""
import re

TOOLS = [
    {
        "slug": "capm-calculator",
        "replacements": [
            ('lang="zh-CN"', 'lang="en"'),
            ('CAPM资本资产定价计算器 | Free ToolBase', 'CAPM Calculator | Free ToolBase'),
            ('CAPM资本资产定价计算器 - Free ToolBase', 'CAPM Calculator - Free ToolBase'),
            ('使用资本资产定价模型计算期望收益率。输入无风险利率、市场收益率和贝塔系数，一键得出资产合理回报。纯前端计算，数据安全。', 'Calculate expected return using the Capital Asset Pricing Model. Input risk-free rate, market return and beta to get fair asset return. Client-side only, data secure.'),
            ('CAPM计算器,资本资产定价模型,期望收益率,贝塔系数,无风险利率,市场溢价,投资估值,金融计算器', 'CAPM calculator,Capital Asset Pricing Model,expected return,beta,risk-free rate,market premium,investment valuation,financial calculator'),
            ('使用资本资产定价模型计算期望收益率。输入无风险利率、市场收益率和贝塔系数，一键得出资产合理回报。', 'Calculate expected return using the Capital Asset Pricing Model. Input risk-free rate, market return and beta to get fair asset return.'),
            ('使用资本资产定价模型（CAPM）计算资产期望收益率。输入无风险利率、市场期望收益率和贝塔系数，一键得出资产的合理回报水平。广泛应用于投资估值和资产定价。', 'Calculate expected return using the Capital Asset Pricing Model (CAPM). Input risk-free rate, expected market return and beta to get the fair return. Widely used in investment valuation and asset pricing.'),
            ('什么是CAPM？', 'What is CAPM?'),
            ('CAPM（Capital Asset Pricing Model，资本资产定价模型）是金融学中用于计算资产期望收益率的经典模型。公式为：E(Ri) = Rf + β × (Rm - Rf)，其中Rf为无风险利率，β为贝塔系数，(Rm-Rf)为市场风险溢价。', 'CAPM (Capital Asset Pricing Model) calculates expected return: E(Ri) = Rf + β × (Rm - Rf). Rf is risk-free rate, β is beta, and (Rm-Rf) is market risk premium. Widely used in finance for asset pricing.'),
            ('贝塔系数β代表什么？', 'What does Beta (β) mean?'),
            ('β衡量资产相对于市场的波动性。β=1表示与市场同步波动；β>1表示波动大于市场（进攻型）；β<1表示波动小于市场（防御型）；β<0表示与市场反向波动。', 'Beta measures volatility relative to the market. β=1 means moving with market; β>1 means more volatile (aggressive); β<1 means less volatile (defensive); β<0 means inverse movement.'),
            ('无风险利率应该用多少？', 'What risk-free rate should I use?'),
            ('通常使用10年期国债收益率作为无风险利率的代理变量。不同国家不同时期数值不同，常见范围在2%-5%之间。', 'Typically the 10-year government bond yield is used as a proxy. Values vary by country and period, commonly 2%-5%.'),
            ('首页', 'Home'),
            ('工具', 'Tools'),
            ('📋 输入参数', '📋 Input Parameters'),
            ('📊 计算', '📊 Calculate'),
            ('🔄 重置', '🔄 Reset'),
            ('📈 计算结果', '📈 Results'),
            ('期望收益率 (CAPM)', 'Expected Return (CAPM)'),
            ('市场风险溢价', 'Market Risk Premium'),
            ('资产风险溢价', 'Asset Risk Premium'),
            ('无需注册 · 纯前端计算', 'No signup · Client-side only'),
            ('纯前端计算，数据不上传服务器', 'Client-side only, no data uploaded'),
            ('复制', 'Copy'),
            ('已复制', 'Copied'),
            ('复制结果', 'Copy result'),
        ]
    },
    {
        "slug": "sharpe-ratio",
        "replacements": [
            ('lang="zh-CN"', 'lang="en"'),
            ('夏普比率计算器 | Free ToolBase', 'Sharpe Ratio Calculator | Free ToolBase'),
            ('夏普比率计算器 - Free ToolBase', 'Sharpe Ratio Calculator - Free ToolBase'),
            ('计算投资组合的夏普比率，衡量风险调整后的收益。输入组合收益率、无风险利率和标准差，评估投资效率。纯前端计算，数据安全。', 'Calculate the Sharpe Ratio of your portfolio to measure risk-adjusted returns. Input portfolio return, risk-free rate and standard deviation. Client-side only, data secure.'),
            ('夏普比率,风险调整收益,投资组合,标准差,夏普指数,金融计算器,投资效率', 'Sharpe ratio,risk-adjusted return,portfolio,standard deviation,Sharpe index,financial calculator,investment efficiency'),
            ('计算投资组合的夏普比率，衡量风险调整后的收益。输入组合收益率、无风险利率和标准差，评估投资效率。', 'Calculate the Sharpe Ratio of your portfolio to measure risk-adjusted returns. Input return, risk-free rate and standard deviation.'),
            ('计算投资组合的夏普比率（Sharpe Ratio），衡量风险调整后的收益表现。输入组合年化收益率、无风险利率和年化标准差，评估每单位风险带来的超额回报。', 'Calculate the Sharpe Ratio to measure risk-adjusted performance. Input annualized return, risk-free rate and standard deviation to evaluate excess return per unit of risk.'),
            ('夏普比率多高算好？', 'What is a good Sharpe Ratio?'),
            ('一般认为：<0为负（低于无风险收益），0-0.5较差，0.5-1.0一般，1.0-2.0良好，2.0-3.0优秀，>3.0卓越。但不同市场环境下标准不同。', 'Generally: <0 is poor (below risk-free), 0-0.5 suboptimal, 0.5-1.0 acceptable, 1.0-2.0 good, 2.0-3.0 excellent, >3.0 outstanding. Context varies by market.'),
            ('夏普比率和索提诺比率的区别？', 'Sharpe vs Sortino Ratio?'),
            ('夏普比率用标准差衡量总风险（上行+下行），索提诺比率只用下行标准差。对于偏态分布的投资组合，索提诺比率更能反映真实风险。', 'Sharpe uses total standard deviation (up+down), Sortino only uses downside deviation. For skewed distributions, Sortino better reflects true risk.'),
            ('年化标准差怎么算？', 'How to annualize standard deviation?'),
            ('年化标准差 = 月收益率标准差 × √12。如果只有日收益率，则×√252。', 'Annual σ = monthly σ × √12. For daily returns, multiply by √252.'),
            ('首页', 'Home'),
            ('工具', 'Tools'),
            ('📋 输入参数', '📋 Input Parameters'),
            ('📊 计算', '📊 Calculate'),
            ('🔄 重置', '🔄 Reset'),
            ('📈 计算结果', '📈 Results'),
            ('夏普比率', 'Sharpe Ratio'),
            ('超额收益率', 'Excess Return'),
            ('无需注册 · 纯前端计算', 'No signup · Client-side only'),
            ('纯前端计算，数据不上传服务器', 'Client-side only, no data uploaded'),
            ('复制', 'Copy'),
            ('已复制', 'Copied'),
            ('复制结果', 'Copy result'),
        ]
    },
    {
        "slug": "beta-calculator",
        "replacements": [
            ('lang="zh-CN"', 'lang="en"'),
            ('贝塔系数计算器 | Free ToolBase', 'Beta Calculator | Free ToolBase'),
            ('贝塔系数计算器 - Free ToolBase', 'Beta Calculator - Free ToolBase'),
            ('计算股票/资产的贝塔系数，衡量系统性风险。输入资产收益率和市场收益率序列，自动计算β值和R²。纯前端计算，数据安全。', 'Calculate Beta coefficient for stocks/assets to measure systematic risk. Input asset and market return series to compute β and R². Client-side only, data secure.'),
            ('贝塔系数,系统风险,股票波动率,CAPM,回归分析,金融计算器,β系数', 'Beta coefficient,systematic risk,stock volatility,CAPM,regression,financial calculator,beta'),
            ('计算股票/资产的贝塔系数，衡量系统性风险。输入资产收益率和市场收益率序列，自动计算β值和R²。', 'Calculate Beta coefficient for stocks/assets to measure systematic risk. Input asset and market return series to compute β and R².'),
            ('计算股票或资产的贝塔系数（β），衡量系统性风险。输入资产和市场月度收益率序列，自动进行回归分析，计算β值、R²拟合度和相关系数。', 'Calculate Beta coefficient (β) for stocks or assets to measure systematic risk. Input monthly return series for regression analysis, computing β, R² and correlation.'),
            ('贝塔系数怎么计算？', 'How is Beta calculated?'),
            ('β = Cov(Ri, Rm) / Var(Rm)，即资产收益率与市场收益率的协方差除以市场收益率的方差。本质上是OLS回归的斜率系数。', 'β = Cov(Ri, Rm) / Var(Rm), the slope coefficient from OLS regression of asset returns on market returns.'),
            ('多少数据点足够计算β？', 'How many data points needed?'),
            ('一般建议至少36-60个月的月度收益率数据。数据太少则统计意义不足，R²偏低。', 'Generally 36-60 months of monthly returns are recommended. Too few points lack statistical significance with low R².'),
            ('β=0是什么意思？', 'What does β=0 mean?'),
            ('β=0表示资产收益率与市场无关，理论上期望收益等于无风险利率。现实中很少有资产β严格为0。', 'β=0 means asset returns are uncorrelated with the market. In theory, expected return equals the risk-free rate.'),
            ('首页', 'Home'),
            ('工具', 'Tools'),
            ('📋 输入参数', '📋 Input Parameters'),
            ('资产月收益率 (% 每行一个)', 'Asset Monthly Returns (% one per line)'),
            ('市场月收益率 (% 每行一个)', 'Market Monthly Returns (% one per line)'),
            ('📊 计算', '📊 Calculate'),
            ('🔄 重置', '🔄 Reset'),
            ('📈 计算结果', '📈 Results'),
            ('贝塔系数 (β)', 'Beta Coefficient (β)'),
            ('R² 拟合度', 'R² (Goodness of Fit)'),
            ('相关系数', 'Correlation'),
            ('数据点数', 'Data Points'),
            ('无需注册 · 纯前端计算', 'No signup · Client-side only'),
            ('纯前端计算，数据不上传服务器', 'Client-side only, no data uploaded'),
            ('复制', 'Copy'),
            ('已复制', 'Copied'),
            ('复制结果', 'Copy result'),
        ]
    },
    {
        "slug": "dividend-calculator",
        "replacements": [
            ('lang="zh-CN"', 'lang="en"'),
            ('股息收益计算器 | Free ToolBase', 'Dividend Yield Calculator | Free ToolBase'),
            ('股息收益计算器 - Free ToolBase', 'Dividend Yield Calculator - Free ToolBase'),
            ('计算股票股息收益率和年化分红收入。输入股价、每股股息和持股数量，一键评估股息投资回报。纯前端计算，数据安全。', 'Calculate dividend yield and annual dividend income. Input stock price, dividend per share and shares held to evaluate returns. Client-side only, data secure.'),
            ('股息计算器,股息率,分红收益,股票分红,每股股息,投资回报,金融计算器', 'dividend calculator,dividend yield,stock dividend,income investing,dividend per share,investment return,financial calculator'),
            ('计算股票股息收益率和年化分红收入。输入股价、每股股息和持股数量，一键评估股息投资回报。', 'Calculate dividend yield and annual dividend income. Input stock price, dividend per share and shares held to evaluate returns.'),
            ('计算股票股息收益率（Dividend Yield）和年度分红收入。输入当前股价、每股年度股息和持股数量，评估股息投资回报率和被动收入潜力。', 'Calculate dividend yield and annual dividend income. Input stock price, annual dividend per share and number of shares to evaluate return and passive income potential.'),
            ('股息率多少算好？', 'What is a good dividend yield?'),
            ('不同行业差异很大：公用事业/REITs通常3%-6%，科技股通常0%-1.5%，消费必需品2%-3%。高股息率（>8%）可能意味着股价大跌或股息不可持续。', 'Varies by sector: Utilities/REITs 3-6%, Tech 0-1.5%, Consumer Staples 2-3%. Yields >8% may signal unsustainable dividends or falling stock price.'),
            ('派息率和股息率有什么区别？', 'Dividend Yield vs Payout Ratio?'),
            ('股息率=每股股息/股价，反映投资回报率；派息率=每股股息/EPS，反映公司将多少利润用于分红。', 'Dividend Yield = DPS/Price (investor return). Payout Ratio = DPS/EPS (how much profit is distributed).'),
            ('中国A股股息率一般多少？', 'What about dividend taxes?'),
            ('上证50成分股平均股息率约2.5%-3.5%，银行股可达4%-6%。港股通标的股息率普遍更高。', 'Dividends are taxed in most countries. US qualified dividends at 0-20%. Tax treatment varies by jurisdiction.'),
            ('首页', 'Home'),
            ('工具', 'Tools'),
            ('📋 输入参数', '📋 Input Parameters'),
            ('当前股价 (元)', 'Current Stock Price ($)'),
            ('每股年度股息 (元)', 'Annual Dividend Per Share ($)'),
            ('持股数量', 'Number of Shares'),
            ('📊 计算', '📊 Calculate'),
            ('🔄 重置', '🔄 Reset'),
            ('📈 计算结果', '📈 Results'),
            ('股息收益率', 'Dividend Yield'),
            ('年度分红收入', 'Annual Dividend Income'),
            ('月均分红收入', 'Monthly Dividend Income'),
            ('总投资金额', 'Total Investment'),
            ('派息率', 'Payout Ratio'),
            ('无需注册 · 纯前端计算', 'No signup · Client-side only'),
            ('纯前端计算，数据不上传服务器', 'Client-side only, no data uploaded'),
            ('复制', 'Copy'),
            ('已复制', 'Copied'),
            ('复制结果', 'Copy result'),
        ]
    },
    {
        "slug": "debt-payoff-calculator",
        "replacements": [
            ('lang="zh-CN"', 'lang="en"'),
            ('债务清偿计算器 | Free ToolBase', 'Debt Payoff Calculator | Free ToolBase'),
            ('债务清偿计算器 - Free ToolBase', 'Debt Payoff Calculator - Free ToolBase'),
            ('制定债务清偿计划，计算还清时间和总利息。输入债务本金、年利率和每月还款额，对比不同还款策略。纯前端计算，数据安全。', 'Create a debt payoff plan. Input principal, APR and monthly payment to calculate payoff time and total interest. Client-side only, data secure.'),
            ('债务清偿,还债计划,信用卡还款,贷款还清,利息计算,债务管理,金融计算器', 'debt payoff,repayment plan,credit card payoff,loan repayment,interest calculator,debt management,financial calculator'),
            ('制定债务清偿计划，计算还清时间和总利息。输入债务本金、年利率和每月还款额，对比不同还款策略。', 'Create a debt payoff plan. Input principal, APR and monthly payment to calculate payoff time and total interest.'),
            ('制定债务清偿计划，计算需要多长时间还清债务以及总利息支出。输入债务本金、年利率和每月还款额，查看详细还款时间表，并获得加速还款建议。', 'Create a debt payoff plan. Input principal, APR and monthly payment to see payoff timeline, total interest, and accelerated payoff suggestions.'),
            ('雪球法和雪崩法哪个更好？', 'Snowball vs Avalanche method?'),
            ('雪球法（先还最小余额）心理激励效果好；雪崩法（先还最高利率）数学上最优，总利息最少。本计算器展示的是固定月供策略。', 'Snowball (smallest balance first) provides psychological wins; Avalanche (highest APR first) is mathematically optimal. This calculator shows fixed monthly payment strategy.'),
            ('为什么月供不足覆盖利息？', 'Why does minimum payment barely reduce debt?'),
            ('当月还款额≤本金×月利率时，还款只够支付利息，本金永远不会减少。这就是信用卡最低还款陷阱——按最低还款还可能需要几十年才能还清。', 'When payment ≤ principal × monthly rate, you only cover interest. This is the credit card minimum payment trap — it can take decades to pay off.'),
            ('提前还款划算吗？', 'Should I pay off debt or invest?'),
            ('如果债务利率>投资收益率，提前还款更划算。信用卡（18%+）应优先还清；房贷（3%-5%）可考虑投资。', 'Compare rates: if debt APR > expected investment return, prioritize payoff. Credit cards (18%+) first; mortgages (3-5%) may allow concurrent investing.'),
            ('首页', 'Home'),
            ('工具', 'Tools'),
            ('📋 输入参数', '📋 Input Parameters'),
            ('债务本金 (元)', 'Principal ($)'),
            ('年利率 (%)', 'APR (%)'),
            ('每月还款额 (元)', 'Monthly Payment ($)'),
            ('📊 计算', '📊 Calculate'),
            ('🔄 重置', '🔄 Reset'),
            ('📈 计算结果', '📈 Results'),
            ('预计还清时间', 'Estimated Payoff Time'),
            ('总利息', 'Total Interest'),
            ('总还款额', 'Total Payment'),
            ('利息占比', 'Interest Ratio'),
            ('加速还款建议', 'Accelerated Payoff'),
            ('如果每月多还10%，可在', 'If you pay 10% more monthly, you can be debt-free in'),
            ('内还清。', '.'),
            ('无需注册 · 纯前端计算', 'No signup · Client-side only'),
            ('纯前端计算，数据不上传服务器', 'Client-side only, no data uploaded'),
            ('复制', 'Copy'),
            ('已复制', 'Copied'),
            ('复制结果', 'Copy result'),
        ]
    }
]

for tool in TOOLS:
    slug = tool['slug']
    src = f'/home/chison/tools-site/{slug}/index.html'
    dst = f'/home/chison/tools-site/en/{slug}/index.html'
    
    with open(src, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for old, new in tool['replacements']:
        content = content.replace(old, new)
    
    with open(dst, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'✅ Created en/{slug}/index.html')