#!/usr/bin/env python3
"""Translate password-generator CN -> EN - Phase 2: remaining Chinese"""
import re

with open('en/password-generator/index.html') as f:
    en = f.read()

# Phase 2: catch remaining Chinese strings
trans_map_2 = {
    '免费在线随机Password Generator，一键生成高Strong度的安全Password。支持CustomPassword Length、多种Character Types、Exclude Similar、Custom Charset。': 
        'Free online password generator — one click for strong, secure passwords. Supports custom length, character types, exclude similar, and custom charset.',
    'Password Generator,Random Password,StrongPassword,Passphrase,passphrase Generator,PIN Code Generator,Password Creator,SecurePassword Generator,Random Password Generator,StrongPassword Generator': 
        'password generator, random password, strong password, passphrase, PIN code, password creator, secure password, random password generator, strong password generator',
    '免费在线Password Generator - 高Strong度Random Password | Passphrase | PIN Code | generate in real-time': 
        'Free Online Password Generator - Strong Random Passwords | Passphrase | PIN Code | Real-time',
    '免费在线Password Generator，使用crypto.getRandomValues真随机算法生成高Strong度Random Password。支持Random Password、Passphrase、PIN Code三种Mode，Custom Charset、Exclude Similar、批量Export。纯前端处理，密码不会上传。': 
        'Free online password generator using crypto.getRandomValues for truly random passwords. Random, passphrase & PIN code modes, custom charset, exclude similar, batch export. Pure frontend — passwords never uploaded.',
    '如何使用Password Generator': 'How to Use Password Generator',
    '首页': 'Home',
    '工具': 'Tools',
    '🔐 在线Password Generator': '🔐 Online Password Generator',
    '免费在线Password Generator，支持': 'Free online password generator, supports ',
    '常规Random Password': 'Random Password',
    'EasyPassphrase': 'Passphrase',
    'PIN Code三种Mode': 'PIN Code modes',
    '字母+Numbers': 'Letters+Numbers',
    '纯Numbers': 'Numbers Only',
    '⚙️ Random Password选项': '⚙️ Random Password Options',
    '包含Character Types': 'Character Types',
    '特殊Symbols (!@#$%^&*)': 'Special Symbols (!@#$%^&*)',
    'Custom Charset': 'Custom Charset',
    '(覆盖上方选择)': '(overrides above)',
    '留空使用上方Character Types，如：': 'Leave empty to use above, e.g.: ',
    '🔗 分享配置': '🔗 Share Config',
    '将当前配置编码到URL，方便分享': 'Encode current settings to URL for sharing',
    '🖨️ 打印卡片': '🖨️ Print Card',
    '打印Format化Password卡片，方便离线安全保管': 'Print formatted password cards for offline safekeeping',
    '📐 网站规则模板：': '📐 Site Policy Templates:',
    '🌐 General16位': '🌐 General 16-char',
    '🏦 银行级': '🏦 Banking Grade',
    '📥 加载示例：': '📥 Load Example:',
    '😊 简单Easy': '😊 Simple',
    '🔑 API密钥': '🔑 API Key',
    '⚡ 8位快速': '⚡ 8-char Quick',
    '🛡️ 究极安全': '🛡️ Maximum Security',
    '💬 Passphrase选项': '💬 Passphrase Options',
    '单词数量': 'Word Count',
    '分隔符': 'Separator',
    '📱 PIN Code选项': '📱 PIN Code Options',
    'PIN长度': 'PIN Length',
    '无Format': 'Plain',
    '每4位space': '4-digit Space',
    '每4位hyphen': '4-digit Dash',
    '每次生成后Auto Copy第一个Password到剪贴板': 'Auto-copy first password to clipboard on each generation',
    'Avg Entropy (位)': 'Avg Entropy (bits)',
    '选择Password Length': 'Select Password Length',
    '（4-128位）': '(4-128 chars)',
    'Drag the slider to': 'Drag the slider to',
    '纯NumbersPIN Code': 'Pure numeric PIN codes',
    '4-16位': '4-16 digits',
    '一键Export': 'One-click Export',
    'dot击Export按钮': 'Click Export to download',
    'TXT、CSV、JSON三种Format下载': 'TXT, CSV, or JSON formats',
    'dot击第一个Password旁的': 'Click ',
    'Auto Copy模式': 'Auto Copy Mode',
    '勾选"Auto Copy"复选框后': 'When "Auto Copy" is checked, ',
    '每次生成Password时第一个Password会Auto Copy到剪贴板，省去手动dot击步骤': 'the first password auto-copies on each generation — no manual clicking needed.',
    'Bank PINs': 'Bank PINs',
    '生成安全的4-6位NumbersPIN Code': 'Generate secure 4-6 digit PIN codes',
    'Memorable Passwords': 'Memorable Passwords',
    '使用Passphrase模式创建既安全又好记的Password': 'Create secure yet memorable passwords with passphrase mode',
    'Password Length比复杂度更重要': 'Password length matters more than complexity.',
    '建议使用至少12位以上的Password，16位为佳': 'Use at least 12 characters; 16 is better.',
    'Passphrase：': 'Passphrase: ',
    '5个随机单词的Passphrase比12位随机字符Password更安全且更容Easy忆': 'A 5-word passphrase is more secure and easier to remember than 12 random characters.',
    '熵值可达100+位': 'Entropy can reach 100+ bits.',
    'Mix Characters': 'Mix Characters',
    '包含Uppercase、Lowercase、Numbers和特殊Symbols的组合，大幅增加暴力破解难度': 'Combine uppercase, lowercase, numbers, and symbols to dramatically increase brute-force resistance.',
    'Generated Passwords真的安全吗？': 'Are generated passwords really secure?',
    '是的。本工具使用浏览器的 crypto.getRandomValues() 方法生成真正的Random Password，所有计算在您本地设备的浏览器中完成，Generated Passwords不会通过网络传输或存储在服务器上。': 
        'Yes. This tool uses the browser\'s crypto.getRandomValues() for true randomness. All computation happens locally — passwords are never transmitted or stored on any server.',
    'Leak Detection是什么？': 'What is leak detection?',
    'dot击Password旁的': 'Click ',
    '基于Password熵值（信息熵）和现代GPU集群每秒1000亿次猜测的能力进行估算。熵值越高，破解所需时间越长。16位含大Lowercase+Numbers+Symbols的Password，熵值约100位，需要数十亿年才能暴力破解。': 
        'Based on password entropy and modern GPU clusters at 100 billion guesses/second. Higher entropy = longer crack time. A 16-char password with uppercase, lowercase, numbers, and symbols has ~100 bits — billions of years to brute-force.',
    'Passphrase vs Random Password，哪个更好？': 'Passphrase vs random password — which is better?',
    '两者各有优势。Passphrase（如 correct-horse-battery-staple）更Easy忆，5个随机单词的熵值可达100+位，安全性极高。Random Password更紧凑但不易记忆。建议对需要手动输入的场景使用Passphrase，对Password管理器Auto Fill的场景使用Random Password。': 
        'Both have advantages. Passphrases (e.g., correct-horse-battery-staple) are easier to remember — 5 random words = 100+ bits. Random passwords are more compact but harder to remember. Use passphrases for manual entry, random passwords for password managers.',
    'PasswordStrong度基于熵值（信息熵）计算。Weak（红色，&lt;30位）→ Medium（橙色，30-50位）→ Strong（黄色，50-70位）→ 非常Strong（绿色，&gt;70位）。16位含所有Character Types的Password通常为"非常Strong"。': 
        'Based on entropy. Weak (red, <30 bits) → Medium (orange, 30-50) → Strong (yellow, 50-70) → Very Strong (green, >70). A 16-char password with all types is usually "Very Strong".',
    'Exclude Similar有什么作用？': 'Why exclude similar characters?',
    'Export的Passwordfile安全吗？': 'Are exported password files secure?',
    '所有Export操作在浏览器本地完成，file直接下载到您的设备，不会经过任何服务器。建议将Export的file加密存储或导入Password管理器后删除原file。': 
        'All exports happen locally in your browser. Files download directly to your device — never touch any server. Encrypt exported files or import to a password manager, then delete the originals.',
    'dot击Password旁的📱按钮，会生成包含该Password的二维码。用手机相机扫描即可获取Password，方便从电脑传输到手机。二维码完全在浏览器本地生成，Password不会上传到任何服务器。': 
        'Click 📱 to generate a QR code. Scan with your phone to transfer from desktop to mobile. QR codes are generated entirely in your browser — passwords are never uploaded.',
    'Each password shows a memorability rating': 'Each password shows a memorability rating',
    '如Passphrase、纯NumbersPIN': 'e.g., passphrases, numeric PINs',
    '非常Strong': 'Very Strong',
    'bits entropy': ' bits entropy',
    '64位十六进制密钥': '64-char hex key',
    '32字符Base32编码': '32-char Base32',
    '字母+Numbers': 'Letters+Numbers',
    '16位无Symbols': '16-char no symbols',
    '纯Numbers': 'Numbers Only',
    '6-16位Numbers串': '6-16 digit string',
    'Memorability评估': 'Memorability Assessment',
    '每个Password附带': 'Each password rated ',
    '综合考虑长度、Character Types、模式': 'Considers length, character types, and pattern',
    '快捷键': 'Shortcuts',
    '复制第一个': 'Copy First',
    '网站规则模板 (6种)': 'Site Policy Templates (6)',
    '📱 二维码分享': '📱 QR Code Sharing',
    'Memorability评分': 'Memorability Score',
    '破解时间估算': 'Crack Time Estimate',
    'Auto Copy模式': 'Auto Copy Mode',
    '历史跨会话保存': 'Cross-session History',
    '500+口令词库': '500+ Word Library',
    '全部工具': 'All Tools',
    '联系我们': 'Contact',
    '隐私政策': 'Privacy',
    '服务条款': 'Terms',
    '关于我们': 'About',
    '在线Password Generator · 纯前端本地生成 · Password绝不上传服务器': 'Online Password Generator · Pure Frontend · Passwords Never Uploaded',
    '问题Feedback': 'Feedback',
    '扫描二维码复制到手机': 'Scan QR to copy to phone',
    '关闭': 'Close',
    '请选择Character Types': 'Please select character types',
    '瞬间': 'instantly',
    '秒': ' seconds',
    '分钟': ' minutes',
    '小时': ' hours',
    '天': ' days',
    '年': ' years',
    '世纪': ' centuries',
    '万年': ' millennia',
    '亿年': ' billion years',
    '字符': ' chars',
    '个Easy': ' Easy, ',
    '个Medium': ' Medium',
    '📊 Avg Entropy': '📊 Avg Entropy: ',
    '位</span><span>🔓 最WeakPassword破解': ' bits</span><span>🔓 Weakest crack: ',
    '请选择Character Types并生成Password': 'Select character types and generate passwords',
    '💡 Passphrase比随机字符更容Easy住且同样安全': '💡 Passphrases are easier to remember and just as secure',
    '💡 不同网站使用不同Password，避免连锁泄露': '💡 Use different passwords for different sites to prevent chain breaches',
    '💡 Password Length比复杂度更重要，至少12位': '💡 Password length matters more than complexity — at least 12 chars',
    '💡 配合Password管理器使用效果最佳': '💡 Works best with a password manager',
    '💡 启用双因素认证(2FA)增加额外保护层': '💡 Enable two-factor authentication (2FA) for extra protection',
    '显示/隐藏Password': 'Show/Hide Password',
    '删除此Password': 'Delete this password',
    '已删除第': 'Deleted password #',
    '个Password': '',
    '生成二维码 - 手机扫描复制': 'Generate QR code - scan with phone to copy',
    '复制': 'Copy',
    '已复制Password': 'Password copied',
    '复制失败': 'Copy failed',
    '检测泄露': 'Check Leak',
    '共': '',
    '字符</div>': ' chars</div>',
    '⏱ 预估破解时间': '⏱ Est. crack time: ',
    '此Password曾在数据泄露中出现过！建议更换': 'This password has appeared in data breaches! Consider changing it.',
    '⚠️ 此Password曾出现在泄露数据库中，建议更换！': '⚠️ This password was found in breach databases. Consider changing it!',
    '未在已知泄露中发现此Password': 'This password was not found in known breaches',
    '✅ 未在已知泄露中发现此Password': '✅ Password not found in known breaches',
    '检测失败，请重试': 'Check failed, please retry',
    '泄露检测失败，请检查网络后重试': 'Leak check failed. Check your network and retry.',
    '🔒 已Auto CopyPassword到剪贴板': '🔒 Password auto-copied to clipboard',
    '重新复制': 'Copy Again',
    '已复制': 'Copied',
    '🔗 配置链接已复制！粘贴分享给他人': '🔗 Config link copied! Share with others',
    '🔗 URL已更新，复制浏览器地址栏即可分享': '🔗 URL updated — copy the address bar to share',
    'General16位': 'General 16-char',
    'Microsoft 365': 'Microsoft 365',
    'Google': 'Google',
    'AWS IAM': 'AWS IAM',
    'Apple ID': 'Apple ID',
    '银行级': 'Banking Grade',
    '✅ 已应用「': '✅ Applied rule: ',
    '」规则：': ' — ',
    '请先生成Password': 'Please generate passwords first',
    '模式': 'Mode',
    '生成时间': 'Generated',
    '✅ 已加载「': '✅ Loaded example: ',
    '」示例配置': '',
    '请至少选择一种Character Types': 'Please select at least one character type',
    'Custom Charset至少需要2个字符': 'Custom charset needs at least 2 characters',
    '没有可Export的Password': 'No passwords to export',
    '已Export': 'Exported',
    '字符集大小': 'Charset size',
    '个唯一字符': ' unique chars',
    '请先生成Passphrase': 'Please generate passphrases first',
    '已Copy All短语': 'All passphrases copied',
    '请先生成PIN Code': 'Please generate PIN codes first',
    '已Copy AllPIN Code': 'All PIN codes copied',
    '已Clear History记录': 'History cleared',
    '已Copy First': 'First copied',
    '无': 'None',
    'Language': 'Language',
}

for cn_text, en_text in trans_map_2.items():
    if cn_text in en:
        en = en.replace(cn_text, en_text)

# Check remaining Chinese
cn_pattern = re.compile(r'[\u4e00-\u9fff]')
remaining = len(cn_pattern.findall(en))

# Show remaining lines
if remaining > 0:
    for i, line in enumerate(en.split('\n'), 1):
        matches = cn_pattern.findall(line)
        if matches:
            print(f'  L{i}: {line.strip()[:120]}')

print(f'\nRemaining CN chars: {remaining}')

with open('en/password-generator/index.html', 'w') as f:
    f.write(en)
print('Written en/password-generator/index.html')